from build import *
qa=json.loads((WORK/'qa_results.json').read_text())
assert qa['cross_document']['result']=='passed'
r=Report('Consistency Audit','DailyKhata_Consistency_Audit.docx','00_Project_Governance')
r.h('Audit conclusion and scope')
r.p('D1 v2.0 and D2 v2.0 are aligned on the reconstructed project baseline. The cross-document audit found no remaining contradiction in their canonical project definition, problem statement, user groups, personas, capability priorities or architectural boundaries. They share 38 distinct scope entries and five persona records. Source uncertainty is retained explicitly and is not presented as verified fact. This conclusion concerns document consistency, not implementation quality, fieldwork authenticity or supervisor endorsement.')
r.p('The audit covers the seven replacement Word documents prepared on 23 September 2026. Original D1 and D2 files and both earlier governance documents remain unchanged. The D3 instructions were read for compatibility only; no Deliverable 3 was created. D1 was completed and audited before D2 authoring began.')
r.h('Workspace inspection and source preservation')
r.p('The recursive pre-authoring inventory contained ten source files. D1 was available as Word and PDF; D2 was available only as PDF. The existing folder structure was retained. References was empty. No spreadsheets, separate research datasets, raw interviews, observation logs, standalone diagram files, application source code or additional project notes were found.')
r.table('Complete original source inventory',['Location','Material and use'],[
 ('00_Project_Governance','DailyKhata_Scope_Baseline_v1.0.docx: existing scope authority, read completely'),
 ('00_Project_Governance','DailyKhata_Documentation_Standard_v1.0.docx: existing formatting authority, read completely'),
 ('01_Deliverable_1','dailykhata-d1.docx: complete source text and tables; historical original preserved'),
 ('01_Deliverable_1','dailykhata-d1.pdf: corresponding six-page submission representation'),
 ('01_Deliverable_1/task','task.txt: D1 objectives and marking criteria'),
 ('02_Deliverable_2','dailykhata-d2.pdf: complete 12-page source, including quotations, personas and elicitation'),
 ('02_Deliverable_2/task','task.txt: official D2 title, required sections and evidence expectations'),
 ('02_Deliverable_2/task','Design Thinking.pdf: six instructional slides on observation, interviews and interpretation'),
 ('02_Deliverable_2/task','Important Links.txt: 19 teaching-video links; identified and retained, not treated as watched or verified research'),
 ('03_Deliverable_3/task','Deliverable 3.pdf: all five pages read for later business, functional and non-functional requirements compatibility')],[1.78,4.24])
r.p('The original D2 stakeholder funnel is represented as an industry-to-stakeholder table in the replacement. It preserves the analytical sequence without retaining the conflicting stakeholder treatment. The teaching slides are instructional material rather than DailyKhata research figures. No new figures were needed, so figure lists are not applicable.')
r.p('SHA-256 hashes were recorded before authoring and compared after reconstruction. All ten original files matched, including the three historical D1/D2 files. Supporting inventory and check records are retained under 00_Project_Governance/reconstruction_work for reproducibility; they are not additional deliverables.')
r.h('Original inconsistencies and selected resolutions')
r.p('DEC-01 to DEC-20 in the Decision Log provide the previous state, selected decision, reason and affected documents. The following register summarises the complete reconciliation. Applied means propagated to the authoritative replacements, not independently confirmed by an interview participant.')
r.table('Reconciliation register',['Decision and original issue','Resolution and justification','Affected documents'],[(a+'\n'+b,c+' '+d,e) for a,b,c,d,e in DECISIONS],[1.9,2.92,1.2])
r.p('Two related source issues are also recorded in the Decision Log. D2 gives ambiguous timing for follow-up interview questions, so the replacement preserves the questions without asserting a separate visit schedule. The D3 rubric heading says 10 marks while its total and components indicate 20.0; the replacement adopts only its requirements workflow, leaving grading clarification to the supervisor.')
r.h('Cross document content checks')
r.table('Content alignment results',['Check','Result and evidence'],[
 ('Project and problem definition','Pass. Identical canonical definition and problem statement occur in D1 and D2. D2 problem statement occupies three rendered lines, within the four-line limit.'),
 ('Users and market','Pass. Three primary user groups; small shopkeepers secondary. Indicative 18 to 50 range is not a verified statistic or eligibility ceiling.'),
 ('Persona names ages and roles','Pass. Ayesha 34, Bilal 27, Hamza 21, Zubair age not recorded, Usman design age 41. The source age 46 is explicitly a disputed source record.'),
 ('Stakeholder classifications','Pass. Family review does not create shared accounts. Shopkeepers can be secondary direct users. D2 adds internal and conditional provider analysis without redefining D1 users.'),
 ('Feature coverage and priorities','Pass. All 38 scope entries match exactly in D1, D2 and Project Scope. Three legacy SS aliases are retained without duplicate requirements.'),
 ('Accounting architecture','Pass. Shared mapping table and wording distinguish labels, categories and accounts. Double-entry journals must balance wherever used; no certification claim.'),
 ('Product semantics and history','Pass. Shared product examples retain original text, brand, product identity, type, category and account. Comparable quantities are required for like-for-like price claims.'),
 ('Assistant capability','Pass. Core financial querying and data-grounded analysis remain mandatory; no money movement. Conversational comparisons are distinct from optional comparison views.'),
 ('Localisation and optional features','Pass. English and Urdu localisation and voice are Should Have. Urdu implementation is not guaranteed. Offline draft entry remains Could Have.'),
 ('Exclusions and future scope','Pass. Identical exclusion and future-scope passages in D1 and D2. No bank, wallet, ERP, POS or shared-household implementation obligation is introduced.'),
 ('Evidence and statistics','Pass with provenance limitation. Existing reported findings and three quotations are retained in D2. Unsupported population estimates are removed as facts. No new research is fabricated.'),
 ('Terminology and language','Pass. Canonical terms, British English review and en-GB Word spelling check applied. Names and product terms explain remaining dictionary flags.'),
 ('Future D3 compatibility','Pass. D2 supplies evidence and scope traceability plus requirement candidates. Formal BR/FR/NFR decomposition and measurable validation remain later work.')],[1.55,4.47])
r.p('Automated checks also compared four shared canonical tables and twelve shared architectural or scope paragraphs for exact equality. Narrative review checked exceptions and qualifications, including optional exports, dedicated household summaries, recurring-spending analysis, future recurring expense creation and future anomaly detection. Matching text alone was not treated as proof of complete consistency.')
r.h('Word document quality control')
r.p('The documents were generated with Word styles and automatic fields, then opened in Microsoft Word to update contents, caption lists and pagination. The supplied renderer could not run because its LibreOffice conversion engine was unavailable. Microsoft Word PDF export and page-image inspection supplied the rendering check. Rendered files are internal QA artefacts, not requested outputs.')
r.table('Formatting and release checks',['Check group','Result'],[
 ('Page layout','Pass. A4; top and bottom 1 inch; left 1.25 inches; right 1 inch.'),('Typography and paragraph spacing','Pass. Visible text uses Times New Roman. Body 12 pt, justified, 1.15 spacing and 6 pt after. Tables, captions and front matter use documented exceptions.'),('Headings and numbering','Pass. Word Heading styles with automatic multilevel numbering; 16/14/12/12 pt hierarchy and bold italic Heading 4. No manually typed heading numbers.'),('TOC and table lists','Pass. Word-generated fields refreshed; displayed entries checked against rendered pages. No manual page-number lists.'),('Header footer and pagination','Pass. Required header and footer; Page X of Y matches page count; no number displayed on cover.'),('Tables and captions','Pass. Numbered captions, grey borders, bold repeated headers, controlled widths and expanding rows. Header-only page fragments found in the first draft were corrected.'),('Page breaks and flow','Pass. Reviewed all final pages for overflow, orphan headings, clipped rows, accidental blank pages and misplaced captions. Front-matter whitespace and final-page remainder are intentional.'),('Figures','Not applicable. The stakeholder sequence is a table; no generated figures or uncited diagrams.'),('Spelling and British English','Pass. Word spelling review performed with British English; flagged names and technical terms reviewed. No unresolved ordinary-word spelling error identified.'),('Prohibited punctuation','Pass. Full generated DOCX XML packages searched for Unicode U+2014; zero occurrences.'),('Scope and traceability','Pass. Shared register, persona table, definitions and exclusions checked; DR candidates link to evidence and SC/SS identifiers.'),('Historical preservation','Pass. All ten source-file hashes unchanged; no output written to the Deliverable 3 folder.')],[1.7,4.32])
r.h('Items requiring human confirmation')
r.p('The project team should confirm Usman\'s actual participant age from primary records; supply interview dates, notes or recordings and consent context; and identify competitor versions, test dates and the unnamed bank application. Until then, D2 describes these as source-reported evidence. The canonical design persona age remains 41, so neither deliverable depends on resolving the conflicting source age to define its user model.')
r.p('The team and supervisor should record actual submission dates, review the reconstructed baseline and document endorsement. The assignment deadline of 25 August 2026 is not treated as a submission date. Later empirical validation must establish receipt-test conditions, target devices, network assumptions and measurable quality targets. These are validation needs rather than unresolved contradictions in the replacement baseline.')
r.h('Release record')
r.table('Authoritative replacement documents',['Document','Purpose'],[
 ('DailyKhata_Project_Scope.docx','Scope authority and complete capability register'),('DailyKhata_Documentation_Standard.docx','Shared Word, language, evidence and change-control rules'),('DailyKhata_Canonical_Terminology.docx','Canonical concepts and persona identities'),('DailyKhata_Decision_Log.docx','Twenty controlled resolutions and human confirmation register'),('DailyKhata_Deliverable_1_v2.0.docx','Market, users, problems, needs, expectations and scope foundation'),('DailyKhata_Deliverable_2_v2.0.docx','Problem, stakeholders, preserved evidence and elicitation traceability'),('DailyKhata_Consistency_Audit.docx','Inspection record, reconciliation, alignment checks and release limitations')],[3.0,3.02])
r.p('The replacement baseline is internally aligned and suitable as the starting point for later requirements work. It does not certify the truth of uncorroborated source research. Any later confirmed correction must be recorded and propagated through the Decision Log and this audit process.')
r.finish()
