from build import *
assert (WORK/'d1_gate.json').exists(), 'D1 must be completed and audited first'

r=Report('Problem Identification, Stakeholder Identification & Requirement Elicitation','DailyKhata_Deliverable_2_v2.0.docx','02_Deliverable_2',2)
r.h('Purpose and inherited baseline')
r.p('This deliverable explains the DailyKhata problem, identifies stakeholders and traces elicitation findings to requirement candidates. It inherits the project definition, persona register and scope priorities from D1 v2.0. The original D2 provides reported fieldwork; the project owner scope supplies capabilities that cannot be attributed to interviews. This is a reconstructed D2, not Deliverable 3 or a claim of implementation. [A2, S2, U1]')
r.p(DEFINITION)
r.h('Problem identification')
r.h('Context and existing process',2)
r.p('The selected users make receipt-based and no-receipt purchases while managing personal or household expenses. In the workflow reported by the original D2, a person keeps a receipt, writes an amount in a diary or phone note, or relies on memory. Recording may happen later, requiring the person to reconstruct the date, amount and purpose. Monthly review then depends on combining scattered records. This describes the project\'s reported qualitative context, not the behaviour of most people in Pakistan. [S2, pp. 2-3]')
r.table('Existing workflow limitations and implications',['Method','Limitation in the reported workflow','DailyKhata implication'],[
 ('Paper receipts and diary','Receipts may be misplaced or become difficult to read; totals and search require manual work','Digitise and review receipt data; keep searchable structured records'),
 ('Phone notes','Free-text records need manual interpretation and aggregation','Represent expenses consistently; provide categories and totals'),
 ('Memory','Small purchases can be omitted or recalled imprecisely','Support quick cash entry and later correction'),
 ('Existing expense applications','Original D2 reports friction entering fields and no item-price view in its tested workflow','Investigate lower-effort capture and item-level history; do not infer universal competitor limitations')],[1.15,2.58,2.29])
r.h('Methods reported in the source',2)
r.p('The original D2 reports approximately one week of short interviews and informal observation. It names Ayesha Tariq, Hamza Sheikh and Usman Raza, and describes 10 to 15 minute in-person or phone conversations. Four initial questions asked about current recording, update frequency, previous attempts that were abandoned, and what would encourage continued use. Additional requirement-focused questions are retained in the elicitation section. [S2, p. 3]')
r.p('Observation reportedly involved family members, roommates and classmates in home kitchens, hostel rooms, the university canteen and a neighbourhood shop. The team watched whether a small purchase was written down, an application opened, a receipt kept or no action taken. Dates, participant counts, event counts and observation sheets are not present. The Design Thinking teaching material supports separating what was seen from how it is interpreted; it does not prove that these observations occurred. [S2, pp. 3, 10; M1]')
r.h('Evidence register and limitations',2)
r.table('Preserved evidence and provenance',['ID and source','What the original reports','Status and permitted inference'],[
 ('EV-01\nS2 p. 3','Ayesha Tariq, homemaker, 34: typing discourages continued tracking; photographs appeal','Source-reported interview statement. Supports lower-effort receipt capture; no general abandonment rate'),
 ('EV-02\nS2 p. 3','Hamza Sheikh, university student, 21: repeated form filling discouraged use','Source-reported interview statement. Supports quick entry; no measured timing threshold'),
 ('EV-03\nS2 p. 3','Usman Raza, shopkeeper, source age 46: speaking an amount could reduce forgotten cash activity','Source-reported statement with conflicting age. Income context is not an expense requirement'),
 ('EV-04\nS2 pp. 3, 10-11','Purchases were often logged later or not at all; recall could be rounded or incomplete','Informal observation narrative, without counts. Supports retrospective entry; no prevalence claim'),
 ('EV-05\nS2 pp. 10-11','Participants preferred photograph or speech to repeated typing and wanted category confirmation','Source-reported follow-up interviews. Supports review; voice priority still follows scope'),
 ('EV-06\nS2 pp. 10-11','Team tested Cashew, Wallet and an unnamed bank app for 30 to 45 minutes per member on Android','Historical comparison narrative. No versions, dates or screenshots; not verified current product facts'),
 ('EV-07\nG1 and U1','Approved scope includes accounting structure, semantic products, assistant breadth, authentication and data maintenance','Documentary authority and design direction, not stakeholder fieldwork')],[1.03,2.68,2.31])
r.p('The available evidence consists of the source document\'s account of fieldwork. No raw transcripts, audio, consent records, dated interview notes, completed questionnaires or observation logs were found. No new fieldwork or survey is asserted in this reconstruction. Design personas and reported participant records must not be treated as interchangeable. Usman\'s canonical persona remains 41 under DEC-01; the source-reported interview age remains flagged for confirmation.')
r.h('Preserved stakeholder statements',2)
r.p('The following quotations are reproduced from the original D2, page 3. They have not been checked against recordings or transcripts. Attribution here records what the source says, not independent verification.')
r.p('Ayesha Tariq: "If I could just take a picture and it sorts itself out, I would actually keep doing it. Typing it all in is why I stop after two weeks."')
r.p('Hamza Sheikh: "I deleted the last app I tried because filling in every field felt like an assignment, not something I would do on my own."')
r.p('Usman Raza: "Even if I could just say the amount out loud when a customer pays, that alone would stop me from losing track."')
r.p('Ayesha\'s time reference describes one attributed experience. Usman\'s reference to a customer payment concerns income, so it does not establish a sales ledger, POS or payment-processing requirement. The useful design theme is low-effort capture, subject to the approved expense scope. [DEC-05, DEC-08]')
r.h('Problem statement',2); r.p(PROBLEM)
r.h('Stakeholder identification')
r.p('The identification chain proceeds from industry to market, market segment, user profile, persona and stakeholder. The table below makes that chain explicit. Primary users have the same priority in both deliverables; secondary does not necessarily mean indirect use. Usman is a secondary direct user, while Zubair is a beneficiary of shared information.')
r.table('Industry to stakeholder identification chain',['Stage','DailyKhata application'],[
 ('Industry','Financial technology, specifically personal expense management'),('Market','Personal expense-management applications for Pakistani users'),('Market segment','Adults managing personal or household expenses with paper receipts and cash. The original approximate 18 to 50 range is indicative, not an eligibility limit.'),('User profile','Smartphone users with varied digital confidence who need low-effort capture, understandable categories and useful expense history'),('Persona','Ayesha Tariq, 34; Bilal Ahmed, 27; Hamza Sheikh, 21; Zubair Hassan, age not recorded; Usman Raza, 41'),('Stakeholders','Primary users, secondary direct users and beneficiaries, advisers, development team, supervisor, conditional technical providers and future bank/payment partners')],[1.2,4.82])
r.h('Personas and user profiles',2); persona_section(r)
r.table('Persona pain points and expectations',['Persona','Pain points','Expectation'],[
 ('Ayesha Tariq','Lost or difficult-to-read receipts; tedious transcription; difficulty comparing grocery prices','Photograph, review and correct a receipt with familiar category labels'),('Bilal Ahmed','Ongoing manual upkeep and scattered monthly records','Find records and ask clear questions about monthly spending'),('Hamza Sheikh','Frequent small purchases without receipts; repetitive forms','Quick text capture, automatic proposals and simple confirmation'),('Zubair Hassan','Difficulty interpreting scattered household records','Understand a summary reviewed with the account holder'),('Usman Raza','Inconsistent petty-cash and supplier-expense records','Capture expenses simply, without an inventory or sales workflow')],[1.2,2.4,2.42])
r.h('Stakeholder matrix',2)
r.table('Stakeholder roles interests needs and impact',['Stakeholder and role','Interest and need','Impact and engagement'],[
 ('Primary: Ayesha, Bilal and Hamza\nUse the expense ledger','Reliable personal or household records; low effort; privacy','High design impact. Review capture, corrections, summaries and assistant answers'),
 ('Secondary direct user: Usman\nRecords shop expenses','Petty cash and supplier-expense visibility','Medium impact within existing expense workflows; reject sales and inventory expansion'),
 ('Secondary beneficiary: Zubair\nReviews shared information','Understandable household totals','Medium reporting impact; no household account permissions required'),
 ('Secondary: accountants and financial advisers\nOptional report recipients','Clear records and exportable summaries','Inform report clarity; no adviser portal or guaranteed engagement'),
 ('Internal: four-student development team\nBuilds and evaluates the FYP','Feasible integration, maintainability and controllable costs','High delivery impact. Maintain traceability, tests and decisions'),
 ('Internal: Nouman Ali and academic evaluators\nSupervision and assessment','Evidence-based work aligned with assignment criteria','High validation impact. Review scope, research evidence and deliverables'),
 ('External technical providers, if selected\nOCR, AI or hosting services','Compatible interfaces and permitted data handling','Affect cost, availability, latency and data exposure. No provider is committed'),
 ('Future: bank and payment partners\nPossible transaction import','Would require reliable integration if later approved','No current implementation role or dependency')],[1.95,1.95,2.12])
r.p('Privacy and regulatory context is a constraint domain, not itself a named stakeholder organisation. The original D2 label is corrected accordingly. No regulator interview, legal compliance assessment or banking certification is claimed. External technical providers are conditional design dependencies, not arbitrary third-party financial integrations. [DEC-17; project-team analysis]')
r.h('Requirement elicitation')
r.h('Interview technique',2)
r.p('Interviews were selected in the source to understand why users stopped recording and which capture methods they would accept. The reported participants were Ayesha, Hamza and Usman. The initial questions asked how spending was recorded, how often it was updated, whether a notebook or application had been abandoned and why, and what would encourage continued use. The reported conversations lasted 10 to 15 minutes in person or by phone. [S2, pp. 3, 10]')
r.p('The source describes revisiting the same participants with three additional questions: whether logging in under 10 seconds would encourage consistent use; whether typing, speaking or photographing was preferred; and what would make an automatically categorised entry trustworthy. It describes these questions both as a later revisit and as following the initial interviews. Without dated records, this reconstruction does not assert a separate visit schedule. No additional participants are inferred.')
r.p('The reported findings emphasise low effort, no-receipt spending and review of proposed categories. The team derives receipt capture, text-based cash entry, manual quick entry, retrospective entry and confirmation from those themes. Voice-based cash entry remains Should Have despite participant interest. The 10-second question is an elicitation prompt, not evidence that such a time is feasible for every receipt. [EV-01 to EV-05; DEC-07, DEC-10]')
r.h('Observation technique',2)
r.p('Observation was selected to examine recording actions at the moment of purchase rather than relying only on recalled habits. The source names informal settings and social groups but gives no event count or participant list. It reports that expenses were commonly entered later, if at all, and that phone notes did not give participants immediate category totals in their workflow. [EV-04]')
r.p('The derived needs are easy retrospective entry, editable dates, correction of saved values, clear category totals and a monthly summary. The team does not infer a numerical omission rate or a causal claim about all users. Any later observation should document what happened before interpreting why it happened. This is a methodological recommendation, not additional completed research. [M1]')
r.h('Existing system analysis',2)
r.p('The original D2 reports that each team member spent 30 to 45 minutes on Android testing Cashew, Wallet and an unnamed bank application. The task was to add a grocery-style expense and look for history for repeated items. It reports repeated typing, limited local label adaptation in that test and no item-price view. No app version, test date, account tier, screenshot or detailed procedure is available. [EV-06]')
r.p('These observations are preserved as historical team-reported findings. They cannot establish that the products currently lack receipt capture, voice entry, category customisation or price history. Mint and Notion-based sheets mentioned in D1 are comparison context, not additional tested systems. The derived DailyKhata choices are locally understandable labels, optional custom labels and item-level price history. The rationale remains useful without asserting competitor inferiority. [DEC-09]')
r.h('Document analysis and scope reconciliation',2)
r.p('For this reconstruction, the original D1, D2, their task instructions, existing governance, Design Thinking slides and D3 brief were read. This document-analysis step reconciled persona facts and priorities and identified capabilities mandated by the owner scope. It supplies authority for authentication, ledger maintenance, the full internal Chart of Accounts, semantic product classification and assistant breadth. These capabilities are not retrospectively attributed to the three interviews. [EV-07]')
r.h('Findings to derived requirement candidates',2)
r.p('The following are D2 elicitation outcomes, ready for later decomposition and validation. They are not a completed D3 specification. DR identifiers are local D2 traceability labels; the SC and SS identifiers remain the stable scope references. Each requirement candidate inherits the priority of its linked capability.')
r.table('Traceability from findings to requirement candidates',['Candidate and basis','Derived behaviour','Scope and priority'],[
 ('DR-01\nEV-01, EV-05, EV-07','Capture or upload a receipt, extract structured values and allow correction before saving','SC-04 to SC-07\nMust Have'),('DR-02\nEV-02 to EV-05','Record a no-receipt expense through a short manual form or text statement, including retrospective entry','SC-08, SC-09\nMust Have'),('DR-03\nEV-03, EV-05','Offer short voice expense capture if feasible','SC-10\nShould Have'),('DR-04\nEV-05, EV-06','Propose transaction and line-item categories; obtain confirmation or correction','SC-11 to SC-13\nMust Have'),('DR-05\nEV-07','Keep an internal Chart of Accounts and stable category-to-account mappings in accounting-compatible records','SC-14 to SC-16\nMust Have'),('DR-06\nEV-04, EV-07','Provide ledger history, search, filtering, category totals, monthly summaries and dashboard','SC-03, SC-17 to SC-20, SC-25\nMust Have'),('DR-07\nEV-06, EV-07','Retain item-level price history and classify products semantically without discarding original identity','SC-21, SC-22\nMust Have'),('DR-08\nS1 and EV-07','Answer spending questions and provide data-grounded conversational analysis','SC-23, SC-24\nMust Have'),('DR-09\nEV-07','Authenticate users, maintain basic profile/settings, protect user records and allow editing/deletion','SC-01, SC-02, SC-26, SC-27\nMust Have'),('DR-10\nEV-06, EV-07','Offer bilingual localisation, exports and custom labels while preserving category mappings','SC-28, SC-29, SS-03\nShould Have'),('DR-11\nEV-04, EV-07','Offer spending visualisations, comparison views and receipt image archiving','SS-04 to SS-06\nShould Have'),('DR-12\nEV-07','Consider user-created categories, offline drafts, reminders and exportable household summaries','SS-08 to SS-11\nCould Have')],[1.18,3.1,1.74])
r.h('Quality expectations and validation needs',2)
r.table('Quality candidates for later measurable validation',['Quality area and source','Expectation','Later validation needed'],[
 ('Usability and performance\nEV-01, EV-02, EV-05','Reduce typing and repeated steps; make processing state and correction clear','Time simple cash entry separately from OCR, review and network delays; set targets after pilot testing'),('Security and privacy\nS1, EV-07','Protect storage, communication and user-specific access, including assistant retrieval','Test authentication, authorisation boundaries, safe uploads and secret handling'),('Device and network behaviour\nSC-30, DEC-11','Remain reasonably usable on ordinary Android-class devices; show failures and permit retry','Specify test device and network conditions; do not presume offline OCR'),('Data integrity\nSC-07, SC-12, SC-16, SC-26','Preserve corrected values, coherent summaries and balanced journals where used','Test mixed receipts, edits, deletion, rounding and category/account mappings'),('Assistant reliability\nSC-23, SC-24','Ground answers in authorised stored data and acknowledge missing data','Compare amounts with ledger calculations; test empty history, ambiguous periods and inaccessible records')],[1.38,2.15,2.49])
r.p('There is no survey, prototype test, focus group or benchmark dataset in the source workspace. No accuracy percentage, retention improvement, concurrency threshold or universal response-time target is therefore reported as measured. These gaps affect empirical validation, not the agreed feature priorities.')
r.h('Authoritative scope and design constraints'); boundaries(r); scope_table(r); architecture(r)
r.h('Validation and compatibility with later requirements work')
r.p('The D1 audit was completed before this D2 was authored. This D2 inherits its project and problem definitions, five canonical personas, three primary user groups and 38 distinct scope entries. The cross-document audit checks those invariants and the differences between current, optional and future capabilities. Document consistency does not confirm the historical interviews or supervisor approval.')
r.p('The D3 brief requires business, functional and non-functional requirements, source traceability and validation. This D2 supplies problems, stakeholder roles, EV evidence identifiers, DR candidates and SC/SS scope links for that later task. The next analysis can decompose each candidate, assign formal IDs and define measurable acceptance criteria after student and supervisor review. The brief contains an inconsistent rubric heading and total; no grading interpretation or numerical example is adopted as a DailyKhata requirement. [A3]')
r.p('Before submission, the team should confirm fieldwork dates and provenance, resolve Usman\'s participant age from source records, identify the competitor test context and obtain supervisor feedback. These actions must update the Decision Log. They do not authorise adding shared household accounts, bank integration or enterprise features.')
r.h('Conclusion'); r.p('The preserved qualitative account points to effort, fragmented records and the need for trustworthy review. The reconstructed baseline responds with receipt and cash capture, user-controlled categorisation, structured accounts, item history and an AI Financial Assistant. Evidence limitations are explicit, every capability retains its priority, and optional or future features remain bounded.')
references(r,True); r.finish()
