from model import *
from build import Report,field,el,Pt,Inches,WD_ALIGN_PARAGRAPH,qn
from docx.enum.section import WD_SECTION_START
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT
validate()
r=Report('Requirements Specification','DailyKhata_Deliverable_3_v1.0.docx','03_Deliverable_3',3,version='1.0')
for p in r.d.paragraphs:
 if p.text.startswith('Project: DailyKhata'):
  p.text='Project: DailyKhata\nDocument: Requirements Specification\nDeliverable: 3\nVersion: 1.0\nStatus: Authoritative Requirements Baseline\nAuthors: DailyKhata Project Team\nSupervisor: Nouman Ali\nAcademic Year: 2026-2027\nRevision date: 23 September 2026\nSubmission date: Not yet recorded\nSupervisor endorsement: Pending review'
  p.alignment=WD_ALIGN_PARAGRAPH.LEFT
 if p.text.startswith('Historical source versions'):
  p.text='Version 1.0, 23 September 2026. Initial formal requirements baseline, derived from governance and Deliverables 1 and 2 v2.0. Formal BR, FR and NFR identifiers begin here. Source files are unchanged. Internal requirements review is complete; stakeholder endorsement and implementation acceptance tests remain pending.'
for e in r.d.element.findall('.//'+qn('w:instrText')):
 if '\\o "1-3"' in (e.text or ''):e.text=e.text.replace('"1-3"','"1-2"')

def para(label,text):
 p=r.d.add_paragraph();p.add_run(label+' ').bold=True;p.add_run(text);return p
def j(v):return ', '.join(v)
def unique(v):return sorted(set(v))
def brfr(b):return [f for f in FR if b in f['br']]
def refs(fs,key):return unique(x for f in fs for x in f[key])
def tab(c,h,rows,w=None):
 if h[0] in ('Scenario','Issue'): rows=[(row[0].split()[0],*row[1:]) for row in rows]
 r.table(c,h,rows,w)
 for row in r.d.tables[-1].rows:
  for c in row.cells:c.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
def split_ids(ids,size=5):return [ids[i:i+size] for i in range(0,len(ids),size)]

r.h('Introduction')
r.h('Purpose and intended use',2)
r.p('This document establishes DailyKhata\'s formal requirements baseline for the project team, supervisor and assessors. It translates the approved problem, user needs and scope into eight business requirements, 69 functional requirements and 26 non-functional requirements. The catalogue supports architecture, database and interface design, implementation and acceptance testing. It specifies intended behaviour; it does not assert that the application has been built or tested. [G1-G5, D1, D2, A3]')
r.p('All 38 canonical scope capabilities are represented, including all 27 Must Have capabilities. Optional requirements retain their approved Should Have or Could Have status. The baseline is feasible as a bounded four-student integration project using existing OCR and language-model capabilities, subject to the dependency and acceptance-target reviews recorded later in this document.')
r.h('Project overview and problem',2);r.p(DEFINITION);r.p(PROBLEM)
r.h('Product boundary',2)
r.p('The primary users are homemakers and household budget managers, university students and salaried professionals in Pakistan. A single account holder records personal or household expenses. Small shopkeepers are secondary direct users for petty cash and supplier expenses. Family members may review information with the account holder or receive a user-exported summary; they do not gain household roles, invitations or collaborative editing rights. The system is mobile-first and targets ordinary Android-class devices. [D1, D2, G1]')
r.p('The current product combines reviewed receipt digitisation, manual and text-based cash entry, an expense ledger, internal accounting mappings, semantic product classification, item-level price history, summaries and a read-only AI Financial Assistant. Voice, bilingual localisation, export, custom labels, extra views and image archive remain optional. Detailed exclusions and future scope appear later and are not current requirements.')
r.h('Requirement conventions',2)
tab('Requirement identifiers and interpretation',['Identifier or term','Meaning'],[
('BR-001 onwards','Business outcome and its rationale; not a list of implementation features.'),('FR-GROUP-001 onwards','Observable functional behaviour. Each record has a priority, source chain and acceptance criterion.'),('NFR-GROUP-001 onwards','Quality condition, measurement method and scope source.'),('EV, DR, SC and SS','Existing D2 evidence, preliminary candidate and approved scope identifiers. D3 links rather than replaces them.'),('Shall','Normative behaviour for a requirement selected for delivery. A Should Have or Could Have statement does not become mandatory because it uses shall.'),('Acceptance target','A proposed FYP gate to review before testing, not a measured performance result.'),('Source and inference','Evidence means what the supplied source reports. Project-team analysis and D3 elaborations are labelled separately.')],[1.4,4.62])
r.p('IDs are persistent. Later deliverables may elaborate them, attach design or test references and record status. Retired IDs must remain in change history and must not be reused. A substantive change records old wording, new wording, reason, source authority, affected IDs and reviewer decision. This document introduces no new major feature and makes no silent change to D1 or D2.')

r.h('Requirements engineering approach')
r.h('Sources and authority',2)
r.p('The workspace was recursively inventoried before writing. The current governance files, D1 v2.0 and D2 v2.0 were read completely, together with the five-page official D3 brief, original deliverables, task sheets, Design Thinking slides and supporting notes. The reference folder contains no additional research. No source code, raw survey dataset, interview transcript or observation log was available. The 17 input files recorded for this task remain byte-for-byte unchanged.')
tab('Source authority and use',['Level','Source','Use in D3'],[
('1','Current governance [G1-G5]','Scope, terminology, priorities, reconciliation decisions and document standard.'),('2','D1 v2.0 [D1]','Project definition, target audience, design personas, problems and market rationale.'),('3','D2 v2.0 [D2]','EV evidence register, DR candidates, stakeholders and elicitation limitations.'),('4','Official D3 brief [A3]','Business, functional and quality requirements, traceability and validation.'),('5','Historical D1 and D2 [H1-H2]','Provenance only where current baseline has reconciled contradictions.'),('6','Task sheets and Design Thinking [M1-M3]','Assignment context and separation of observation from interpretation.'),('7','External security guidance [X1-X3]','Limited quality-control rationale, never authority for new product features.')],[.45,2.05,3.52])
r.h('Elicitation and analysis',2)
r.p('D2 reports interviews, observation and existing-system examination. This D3 performs documentary analysis of those findings rather than claiming additional stakeholder work. Capture friction supports BR-001; difficulty reconstructing coherent histories supports BR-002 and BR-003. Product semantics, the full internal Chart of Accounts and assistant breadth also rely explicitly on the approved scope. The source chain remains visible even where fieldwork does not establish a capability. [D2, EV-01 to EV-07]')
r.p('Analysis separated outcomes from behaviour, decomposed receipt processing from review and commitment, and distinguished local category labels from categories and accounting accounts. Repeated concepts were consolidated: saved-data maintenance is defined once in the ledger group, then reused by summary, price and assistant requirements. Dependencies were checked so no Must Have requirement needs an optional capability. The internal model was checked before Word authoring for unique IDs, coverage, valid references, duplicate statements and priority conflicts.')
r.h('Classification and prioritisation',2)
tab('Priority rules inherited from governance',['Priority','Delivery interpretation','Rule for dependencies'],[
('Must Have','Minimum successful DailyKhata FYP.','Cannot depend on a Should Have or Could Have feature.'),('Should Have','Intended but may be deferred with a recorded reason.','May depend on core functionality or other selected Should Have features.'),('Could Have','Optional if time and technical capacity permit.','May depend on a selected higher-priority capability; record the dependency.'),('Future Scope','Potential later work, not a current commitment.','No current acceptance requirement is created.'),('Out of Scope','Explicitly excluded from the current project.','Mentioned only to establish the boundary.')],[1,2.6,2.42])
r.p('BR-001 includes optional voice as an additional route to a core outcome. This does not make voice Must Have. Likewise, Should Have presentation outcomes can draw on core data without requiring optional screens for core assistant answers. Shared quality controls apply to optional functionality only when that functionality is implemented. NFR-COMP-002, the dedicated localisation quality requirement, is itself Should Have.')
r.h('Validation and traceability method',2)
r.p('The traceability chain is problem, stakeholder need, evidence or documentary authority, DR candidate, BR outcome, FR behaviour, NFR quality condition and acceptance test. Every FR identifies its source, scope, business outcome and quality links. The four traceability matrices provide reverse lookup. Validation here means requirements inspection and model checks; user trials, software tests, student verification and supervisor endorsement are planned acceptance activities, not completed research. [A3]')

r.h('Stakeholder and evidence foundation')
r.h('Canonical user profiles',2)
tab('Canonical personas inherited from D1 and D2',['Persona','Age and role','Classification'],[(p[0]+' '+p[1],p[2]+'; '+p[3],p[4]) for p in PERSONAS],[1.45,3.12,1.45])
r.p('Ayesha needs household visibility and receipt capture; Hamza needs a short cash-entry path; Bilal needs searchable monthly records. Usman reuses the expense workflow for petty cash and supplier purchases. Zubair is a secondary beneficiary of shared information, with age not recorded. These are design profiles, not five verified interview participants. Usman\'s canonical design age is 41 under DEC-01; the original D2 participant age of 46 remains an unresolved source discrepancy. Bilal and Zubair are not reported interviewees. [G3-G5, D1, D2]')
r.h('Other stakeholders and responsibilities',2)
tab('Stakeholder interests and requirements responsibilities',['Stakeholder','Classification and interest','Engagement'],[
('Four project students','Internal developers and analysts; implementation feasibility and traceability.','Verify source interpretation, maintain requirement IDs, implement and record tests.'),('Nouman Ali','Internal academic supervisor; scope and academic quality.','Review requirements and proposed targets; endorsement is not yet recorded.'),('Family beneficiaries and advisers','Secondary information users; understandable expense summaries.','Review user-shared output without privileged application roles.'),('Selected OCR AI and storage providers','Conditional external technical dependencies; service constraints and data processing.','Review interfaces, cost, retention and failure behaviour before selection.'),('Bank and payment partners','Future stakeholders only.','No current integration or delivery dependency.')],[1.35,2.55,2.12])
r.h('Evidence register and limitations',2)
tab('Preserved D2 evidence register',['ID','Reported finding','Provenance and limitation'],[(k,*v) for k,v in EV.items()],[.65,2.55,2.82])
r.p('D1 also supplies the original assistant and target-market intent, especially for DR-08. The qualitative evidence supports design rationale, not market size, population prevalence or quantified benefit. No fabricated participant, survey result, quotation, benchmark or user test is included. The historical competitor comparison is not evidence about current products. The original statement about a customer paying is retained only as cash-capture context and never becomes sales or payment scope.')

r.h('Business requirements')
r.h('Business goals and catalogue',2)
r.p('The outcomes concern reduced recording effort, coherent records, spending understanding, product comparison, privacy and ordinary-device use. Optional outcomes improve presentation and recording habits. Success indicators below describe observable outcomes to evaluate, not claimed improvements already measured. The related scope and functional IDs make each outcome operational.')
for bid,title,statement,obj,why,stake,priority,success in BR:
 r.h(title,3);para(bid+' | '+priority,statement)
 para('Objective and rationale:',obj+' '+why)
 para('Stakeholders and source:',stake+'. '+j(refs(brfr(bid),'evidence'))+'; '+j(refs(brfr(bid),'dr'))+'. DR-08 additionally retains original D1 [H1] intent.' if bid=='BR-003' else stake+'. '+j(refs(brfr(bid),'evidence'))+'; '+j(refs(brfr(bid),'dr'))+'.')
 para('Success indicator:',success)
 para('Scope and downstream behaviour:',j(unique(refs(brfr(bid),'scope')+(['SC-30'] if bid=='BR-006' else [])))+'. '+j([f['id'] for f in brfr(bid)])+'.')
r.h('Business requirement analysis',2)
r.p('The first six outcomes define the minimum product purpose. BR-007 and BR-008 add optional benefits without changing the intended market. No requirement promises measured financial savings, user retention or a market share. A saving suggestion is useful only when its arithmetic and assumptions are visible; the user remains responsible for deciding what to do. An expense record can be internally coherent even when the user has not recorded all real-world spending, so the assistant must distinguish recorded spending from total actual spending.')

r.h('Functional requirements')
r.h('Shared workflow and data rules',2)
r.p('A capture route produces a draft. Extraction and interpretation propose values. The account holder reviews required fields, resolves inconsistent totals and confirms categories, then explicitly commits the expense. Only an active committed expense participates in summaries and price history. Every protected operation inherits the authentication boundary. The common actor, preconditions, trigger and rationale stated for each subsystem apply to its records; each requirement supplies its own behaviour, acceptance oracle and failure path.')
tab('Controlled D3 elaborations and interpretation rules',['Rule','Normative interpretation and reason'],[
('E-01 Identity and dates','Stable opaque identifiers distinguish account, expense, item, category and account mapping. Use the expense calendar date for summaries and a separate creation timestamp. Resolve relative dates using Asia/Karachi. Today may be a visible default in manual entry; missing receipt dates require confirmation. This formalises retrospective entry.'),
('E-02 Amounts and currency','Baseline expenses are positive PKR amounts represented exactly to two decimal places. A manually entered total is permitted when OCR fails. Refunds, income workflows, foreign-currency conversion and scheduled future expenses are not added by this specification.'),
('E-03 Receipt reconciliation','The payable transaction total is authoritative after review. Allocate it across the categorised purchase lines, including explicit user-reviewed discount, tax or rounding adjustments. Keep adjustments distinct from products and exclude them from product-price history. Block saving until the allocations equal the total; do not invent a missing product to balance it.'),
('E-04 Counting and categories','For an itemised receipt, category totals sum its allocations; for an unitemised expense, its single allocation equals the total. Never sum both parent and line totals. The transaction primary category supports display and search; a category filter also matches a line allocation. It does not replace mixed-item allocations.'),
('E-05 Product quantities','Keep purchased count, pack size, unit price and line total distinct. Unknown quantity is not silently one. Convert known compatible units, such as g to kg, and show the comparison basis. Separate brands and pack identities even under the same canonical product type.'),
('E-06 Corrections and deletion','Preserve original OCR text alongside corrected values while a record exists. Deleting the expense removes its financial content under NFR-PRIV-003; source preservation does not mean retaining deleted content forever. Ordinary history excludes deleted records. Corrections invalidate dependent calculated results.'),
('E-07 Account framework','Maintain the five conventional account types: asset, liability, equity, income and expense. The FYP exposes only expense-management workflows; cash is an asset account. Recognising an account type does not create sales, payroll or full financial-statement functionality. Final hierarchy and codes remain architecture decisions.'),
('E-08 Settings and credentials','A display name and default summary month give a bounded interpretation of basic profile and settings. Login identifier format and credential rules are documented at implementation review; if passwords are managed locally, use at least 12 characters and permit at least 64. These proposed details do not add social login or account administration.'),
('E-09 Draft lifetime','Core draft recovery is limited to the current open authenticated session. Surviving application restart without connectivity is the Could Have offline-draft feature. Pending drafts never count as expenses. Optional archive retention does not make permanent image storage core.'),
('E-10 Optional data output','CSV and/or PDF means at least one format, not both. If CSV is selected, user-supplied text beginning with formula-control characters must be exported as inert text and fields escaped correctly. Household output remains an account-holder-controlled selection, not a shared-account service.')],[.85,5.17])
r.p('These are D3 project-team elaborations of approved capabilities, not additional interview findings. Numerical and platform choices are proposed FYP acceptance boundaries to confirm before implementation. Any change to them must use the persistent IDs and change-control rule. None changes a source persona, capability priority or current-versus-future decision.')
for group,meta in GROUPS.items():
 title,actor,pre,trigger,why,nfr=meta
 r.h(title,2)
 para('Context:',why)
 para('Actor and preconditions:',actor+' '+pre)
 para('Trigger and common flow:',trigger+' The specific requirement below defines the observable result; invalid operations follow its failure path and do not imply a successful save.')
 fs=[f for f in FR if f['group']==group]
 for f in fs:
  r.h(f['title'],3)
  para(f['id']+' | '+f['priority'],f['statement'])
  para('Trace and rationale:',j(f['br'])+'; '+j(f['scope'])+'; '+j(f['dr'])+'; '+j(f['evidence'])+'. '+('Original D1 [H1] also supports assistant intent. ' if 'DR-08' in f['dr'] else '')+'This behaviour implements the subsystem purpose above and the linked business outcome.')
  para('Acceptance and expected result:',f['acceptance'])
  para('Alternative or failure:',f['failure'])
  para('Dependencies and quality:',(j(f['dependencies']) if f['dependencies'] else 'No earlier functional service required; authentication infrastructure is needed')+'. '+j(f['nfr'])+'.')
r.p('Dependency references identify service contracts rather than mandatory screen order. OCR can receive a camera photograph or an uploaded image. Product and assistant records reuse the authoritative ledger and calculation contracts. Optional features never sit on the dependency path needed to complete the Must Have capture-to-summary workflow.')

r.h('Non functional requirements')
r.h('Measurement conditions and status',2)
r.p('All numerical thresholds, test-set sizes, device versions, session limits and retention intervals in this section are Proposed acceptance targets for the FYP. They were selected through requirements analysis, not measured in existing fieldwork. Students and supervisor should confirm them using an early pilot. They become delivery gates when this baseline is accepted; any revised target requires a recorded change rather than a silent relaxation. All described tests remain to be executed.')
tab('Acceptance environments and fixtures',['Fixture','Definition and measurement control'],[
('T1 Ordinary device and network','Android 11-class device, 4 GB RAM, at least a 360 CSS-pixel-equivalent viewport; one newer Android version. Choose and record native or mobile-web delivery. Test network: at least 10 Mbps down, 2 Mbps up and approximately 100 ms round-trip latency. Record actual conditions, device, build, cold/warm state and provider configuration.'),
('T2 Capacity and ledger','Ten isolated test accounts, each with 1000 active expenses and up to ten line items per receipt. Run 20 minutes at one request per account every five seconds, 20 percent writes and the remainder history, search and summary reads. Verify all committed records and report rejected requests separately.'),
('T3 Security and privacy','Two accounts with deliberately overlapping merchant and product names but distinct private records; expired sessions, altered object identifiers, malicious filenames, invalid images and cross-account assistant prompts. Include receipt text attempting to override retrieval instructions.'),
('T4 Financial oracle','Controlled PKR records with known dates, categories, product identities and expected arithmetic. Include empty data, two periods, zero baseline, repeated expenses, mixed receipt, missing unit, corrected item and deleted transaction. Reference acceptance scenarios in the validation section.'),
('T5 Receipt extraction','Twenty consented or synthetic printed receipts, clearly labelled by origin, with 3-12 purchase lines each, legible English or Latin-script text, varied layouts and known payable totals. Use two independent annotation passes and reconcile differences. Keep several blurred/cropped images separate for failure-path tests. Urdu OCR is not implied by Urdu interface support.'),
('T6 Prospective user and language review','Five recruited trial users spanning the three primary groups for core tasks; a competent bilingual reviewer for optional Urdu output. Record consent, task script, actual outcomes and defects. These participants have not yet been recruited or tested.')],[.9,5.12])
r.p('Performance measurements separate the application\'s processing time, external provider latency and total visible waiting time. A timeout is a bounded failure response, not a promise of successful OCR or AI completion in 60 seconds. The controlled calculation suite verifies defined answers; it cannot establish perfect general language-model accuracy. Supported-receipt fidelity is measured before correction, while successful end-to-end recording also requires a usable correction path.')
NAMES={'PERF':'Performance','SEC':'Security','PRIV':'Privacy','USE':'Usability','REL':'Reliability','DATA':'Data integrity','COMP':'Compatibility and localisation quality','MAINT':'Maintainability','SCAL':'Academic capacity'}
for g,title in NAMES.items():
 r.h(title,2)
 for n in [x for x in NFR if x['group']==g]:
  r.h(n['title'],3);para(n['id']+' | '+n['priority'],n['statement'])
  para('Source and rationale:',j(n['scope'])+'; approved scope [G1, EV-07] and D2 quality expectations. '+('External guidance is supporting security practice, not a new stakeholder finding. ' if g=='SEC' else '')+'This condition constrains the linked functional behaviours in the traceability matrix.')
  para('Verification:',n['test'])
r.p('No uptime percentage, million-user scale, banking-grade security claim or vendor-specific stack is required. Protected financial storage and correct calculations are mandatory; the selected implementation must demonstrate them in the defined finite tests. If the team cannot meet a proposed target, the result is a documented acceptance issue requiring review, not permission to remove its underlying Must Have capability.')

r.h('Requirement prioritisation')
counts=collections.Counter(f['priority'] for f in FR);nc=collections.Counter(n['priority'] for n in NFR)
tab('Catalogue totals by priority',['Priority','BR','FR','NFR','Scope capabilities'],[(p,sum(b[6]==p for b in BR),counts[p],nc[p],sum(s[2]==p for s in SCOPE)) for p in ['Must Have','Should Have','Could Have']],[1.7,.7,.7,.7,2.22])
r.p('Implement and test one complete Must Have path first: authenticate, capture or enter, review, classify, reconcile, save, retrieve and summarise. Extend this path with product history and the assistant without postponing those core capabilities into optional scope. Optional voice and localisation can be evaluated independently once their shared core contracts work. Defer optional work explicitly if it threatens completion of the Must Have baseline.')
r.p('Scope aliases are unchanged: SS-01 means SC-10, SS-02 means SC-29 and SS-07 means SC-28. They are traceability aliases and are not additional counted capabilities. Dedicated comparison views are Should Have; conversational period comparisons remain Must Have. Automatic recurring transaction creation, predictive anomaly detection and advanced autonomous recommendations remain future scope.')

r.h('Requirements traceability')
r.h('Evidence to formal requirements',2)
r.p('The following matrix preserves D2 candidate provenance. EV descriptions are defined in the evidence register. The DR-08 row additionally retains original D1 [H1]. NFR lists are the union of quality links for the row\'s functional requirements; their exact functional applicability is given in the functional-to-NFR matrix. Scope authority [G1] applies to all rows without being misrepresented as an interview. Repeated evidence links are deliberate many-to-many traceability.')
rows=[]
for dr,(title,evs) in DR.items():
 fs=[f for f in FR if dr in f['dr']]
 rows.append((dr+'\n'+title,j(evs)+(' + H1' if dr=='DR-08' else ''),j(refs(fs,'br')),j(f['id'] for f in fs),j(refs(fs,'nfr'))))
# Use a landscape section only for the dense evidence matrix.
sec=r.d.add_section(WD_SECTION_START.NEW_PAGE);sec.page_width=Inches(11.69);sec.page_height=Inches(8.27)
sec.different_first_page_header_footer=False
tab('Evidence and D2 candidates traced to formal requirements',['D2 candidate and finding','Source evidence','Business outcome','Functional requirements','Quality requirements'],rows,[1.4,1.05,1.05,3.25,2.69])
sec=r.d.add_section(WD_SECTION_START.NEW_PAGE);sec.page_width=Inches(8.27);sec.page_height=Inches(11.69);sec.different_first_page_header_footer=False
r.h('Business to functional requirements',2)
rows=[]
for b in BR:
 for batch in split_ids(brfr(b[0]),7):
  rows.append((b[0]+'\n'+b[1],j(f['id'] for f in batch),'; '.join(p+': '+str(sum(f['priority']==p for f in batch)) for p in ['Must Have','Should Have','Could Have'] if any(f['priority']==p for f in batch))))
tab('Business outcomes and supporting functional requirements',['Business requirement','Functional requirements','FR priorities in row'],rows,[1.45,3.32,1.25])
r.h('Functional to quality requirements',2)
rows=[]
reason={'AUTH':'Credential and access boundary','PROFILE':'Persistent settings and device response','CAPTURE':'Safe input and visible processing','OCR':'Fidelity provenance and bounded waiting','REVIEW':'Correction and input clarity','TXN':'Low-effort valid monetary entry','VOICE':'Reviewed optional speech path','CAT':'Stable confirmed classifications','COA':'Reconciled persistent accounting data','PRODUCT':'Separate identities and provenance','PRICE':'Comparable quantities and current history','LEDGER':'Atomic owned records and coherent revisions','DASH':'Correct totals and readable timely views','AI':'Grounded authorised answers and service failure','REPORT':'Owned consistent exported data','LOC':'Equivalent language meaning and layout','OFFLINE':'Protected drafts and single commitment','REMIND':'Understandable optional notification controls'}
for f in FR:rows.append((f['id'],j(f['nfr']),reason[f['group']]))
tab('Functional requirements and applicable quality conditions',['Functional ID','NFR IDs','Reason'],rows,[1.17,3.05,1.8])
r.h('Scope to formal requirements',2)
rows=[]
for sid,title,pri in SCOPE:
 ids=[f['id'] for f in FR if sid in f['scope']]+[n['id'] for n in NFR if sid in n['scope']]
 rows.append((sid+'\n'+pri,title,j(ids)))
tab('Complete approved scope coverage',['Scope and priority','Capability','Formal requirements'],rows,[1.02,2.4,2.6])
r.p('All 38 scope capabilities have at least one formal requirement. SC-30 is primarily a quality capability, so its direct coverage is chiefly through device, usability, performance and capacity NFRs. Those NFRs constrain the core functional workflows through the preceding matrix. No feature disappears merely because it is represented as a quality requirement.')

r.h('Assumptions constraints and dependencies')
r.h('Assumptions',2)
tab('Assumptions and consequences if false',['ID','Assumption','Consequence and response'],[
('AS-01','Internet is available for selected cloud OCR and assistant operations.','If unavailable, show failure and offer manual entry; optional offline drafts do not promise offline AI.'),('AS-02','Users can provide legible supported printed receipt images and review uncertain output.','Poor images use recapture or manual correction. No universal handwriting or Urdu OCR promise is made.'),('AS-03','The team can access an affordable OCR and language-model option.','Validate cost and limits early; use replaceable interfaces and test substitutes. Budget and vendor are not yet established.'),('AS-04','A representative Android device and consented trial users can be obtained.','Document any emulator-only or unrepresentative evaluation and seek the missing validation rather than claiming it occurred.'),('AS-05','Stored records may be incomplete relative to real spending.','Summaries and suggestions explicitly describe recorded data and their date ranges.')],[.65,2.5,2.87])
r.h('Constraints',2)
r.p('The project is a four-student BS Computer Science FYP at Beaconhouse National University for academic year 2026-2027 under Nouman Ali. The approved scope, single-account boundary and existing delivery priorities constrain implementation. No exact development budget or confirmed submission deadline is established for D3. The team must select a financially feasible deployment during architecture work; this document does not invent a budget ceiling or a semester delivery schedule.')
r.p('The interface is oriented to personal and household expenses, not journal-entry operators. The baseline currency is PKR and the initial interface can be English. Full English and Urdu localisation is Should Have. Privacy, source provenance, corrected categories and coherent monetary totals are constraints on every implementation choice. No vendor, programming language, mobile framework or database is mandated.')
r.h('Technical dependencies',2)
tab('Dependency contracts and acceptance evidence',['Dependency','Required contract','Risk and validation'],[
('Identity and storage','Account identity, protected operations, stable records, atomic save and version-aware revisions.','Early two-account and interrupted-save tests; inspect ownership and storage configuration.'),('OCR component','Supported image to original text and structured candidates, explicit errors and missing fields.','Evaluate T5 before optional feature work; retain manual fallback and measurable provider latency.'),('Category and product interpretation','Proposed classifications with uncertainty and separate identities.','Use local vocabulary and controlled fixtures; preserve user corrections.'),('AI model and retrieval','Natural-language question to bounded authorised retrieval and explainable answer; read-only access.','Verify deterministic calculations separately, inspect payloads and test prompt-based boundary violations.'),('Device and network','Camera/file input, readable core UI and observable network states.','Run actual Android acceptance scenarios and failure injection.'),('Optional speech and export','Speech produces editable text; export produces an owned data selection.','Evaluate only if selected; no core workflow depends on them.'),('Optional localisation and notifications','Translated strings, RTL rendering and local scheduling permissions.','Bilingual review and device-permission tests; defer explicitly if not validated.')],[1.1,2.55,2.37])

r.h('Out of scope');r.p(EXCLUDED)
r.p('These exclusions apply to the current delivery. Internal expense-account mappings do not imply payroll, commercial accounting or tax filing. An assistant that explains recorded spending does not control financial accounts. A shopkeeper\'s expense entry does not create inventory, sales or payment-processing functionality.')
r.h('Future scope');r.p(FUTURE)
r.p('Future work requires a new approved scope decision and traceability update. Analysis of repeated recorded expenses is currently supported; creating recurring expenses is future work. Descriptive observations about high recorded spending are current; predictive anomaly infrastructure is future work. Potential deeper Urdu support is distinct from the currently optional bilingual interface and Urdu interaction.')

r.h('Requirements validation')
r.h('Completed requirements inspection',2)
tab('Internal review results and limits',['Criterion','Review performed','Result and limit'],[
('Correctness and necessity','Compared significant project facts and requirement purpose with governance, D1 and D2.','Aligned with the current baseline; fieldwork authenticity and supervisor endorsement remain unverified.'),('Completeness','Checked all 38 scope IDs and all 27 Must Have capabilities against formal coverage.','No uncovered scope capability; all optional capabilities retain their classifications.'),('Unique identification','Checked 8 BR, 69 FR and 26 NFR IDs and statements in the internal model.','103 unique formal IDs; no duplicate FR statement or unresolved reference.'),('Priority consistency','Compared FR scope priority and dependency direction.','55 Must Have, 10 Should Have and 4 Could Have FRs; no Must Have dependency on optional functionality.'),('Traceability','Checked all FR business, scope, DR, evidence and NFR links; checked every NFR has a functional link.','No orphan FR or NFR. Documentary authority is distinguished from reported fieldwork.'),('Clarity and testability','Reviewed shall statements, acceptance oracles, exceptions and proposed measurement conditions.','Every FR has an observable acceptance result; every NFR has a verification method. Targets await pilot review.'),('Feasibility','Reviewed each subsystem against a four-student integration approach.','Bounded implementation is plausible; OCR quality, AI grounding, provider cost and evaluation access remain material risks.'),('Evidence integrity','Compared EV and DR provenance with D2 and historical-source cautions.','No new interview, survey, user-test result, market statistic or implementation claim is asserted.'),('Source preservation','Compared hashes against the pre-authoring input manifest.','All 17 recorded input files are unchanged. D1 and D2 have not been edited.')],[1.1,2.35,2.57])
r.h('Cross document consistency decisions',2)
tab('Cross document facts checked for continuity',['Topic','D3 treatment','Baseline decision'],[
('Project and users','Same definition, problem and three primary groups; same five personas and ages.','D1 and D2; DEC-01 to DEC-04.'),('Evidence discrepancy','Usman persona is 41; participant age 46 stays a source issue. No new age for Zubair.','DEC-01 and DEC-03.'),('Capture and categories','Manual and text core; voice optional; user confirmation required.','DEC-06 and DEC-07.'),('Accounting','Stable accounts, mappings and reconciliation; balanced journals wherever used.','DEC-17; E-03 and E-07 elaborate, not certify.'),('Product semantics','Separate source text, corrected name, identity, brand, type, category and account.','DEC-20; deletion retention does not imply permanent image archive.'),('Assistant and comparisons','Core conversational comparisons and historical patterns; optional dedicated views.','DEC-13; future predictive systems remain excluded.'),('Localisation and connectivity','Urdu and voice remain Should Have; offline drafts Could Have.','DEC-07, DEC-11 and DEC-14.'),('Households and shopkeepers','Single account, user-shared output, expense-only shopkeeper use.','DEC-03 to DEC-05.'),('Scope and identifiers','All SC/SS priorities preserved; aliases retained. Formal IDs begin in D3.','G1 and D2; DEC-14.'),('Numerical elaborations','Performance, capacity, receipt-set, session and retention values are proposed targets.','DEC-10 and D2 quality expectations; no past benchmark claim.')],[1.25,3.32,1.45])
r.h('Feasibility and implementation risk',2)
tab('Subsystem feasibility review',['Subsystem','Complexity and dependency','Data and testing','Practical boundary'],[
('Identity profile and ledger','Moderate; authenticated storage and atomic revisions.','Two-account fixtures, stale edits and interrupted saves.','Use one account model and one authoritative ledger.'),('Receipt OCR and review','High integration risk; image quality and provider extraction.','T5 annotated receipts plus unreadable inputs.','Printed supported images; review and manual completion remain core.'),('Categorisation and accounts','Moderate; local taxonomy and reconciled allocations.','Mixed-category receipts, corrections and account mappings.','Fixed local categories first; no business accounting interface.'),('Product semantics and prices','High data-quality risk; identity and unit normalisation.','Detergent brands, pack sizes, missing units and corrections.','Small curated product-type vocabulary can support the initial evaluation; preserve unknown values.'),('Dashboard search and export','Moderate; reuse ledger queries.','Known totals, filters and optional file inspection.','Core summary first; dedicated visuals and exports follow priorities.'),('AI Financial Assistant','High; bounded retrieval, model dependency and reliable arithmetic.','Controlled questions, missing data, cross-account and injection cases.','Use existing models, deterministic calculations and read-only tools; no model training commitment.'),('Optional capabilities','Variable; speech, RTL, local storage and notification permissions.','Bilingual review, offline replay and permission denial.','Deliver only selected optional features after the Must Have path passes.')],[1.05,1.85,1.7,1.42])
r.p('Work can be divided into capture and review, ledger and accounting, product and price data, and assistant and presentation. These are possible work areas rather than assignments to named students. Integration tests and source review are shared responsibilities. A service substitution is acceptable if the same behavioural contracts pass; dropping an approved Must Have capability requires an explicit scope decision.')
r.h('Acceptance scenarios and expected calculations',2)
tab('Executable acceptance scenarios for later implementation testing',['Scenario','Fixture and action','Expected result and linked requirements'],[
('AT-01 Receipt review','Use a clear receipt with rice 100 and detergent 50; process, correct categories and confirm.','Draft does not count. Saved total is 150, Ration is 100 and Household Supplies is 50. FR-OCR-001 to 007, FR-REVIEW-001 to 003, FR-CAT-001 to 004, FR-LEDGER-001, NFR-DATA-001.'),
('AT-02 Cash and dates','Enter rickshaw fare 120 yesterday through text, then an expense dated last month through manual entry.','Both require review; the local dates are explicit and each belongs to its expense month. FR-TXN-001 to 003, FR-DASH-002.'),
('AT-03 Reconciliation','Receipt total 150 with item totals 160 due to a printed discount of 10. Review adjustment allocations before saving.','Final category allocations total 150; the discount is not a product-price record. Unresolved mismatch blocks save. FR-COA-003, FR-LEDGER-001, NFR-DATA-001.'),
('AT-04 Double entry','When selected, record groceries paid from cash for 2500; attempt a journal with credits 2400.','Valid journal balances at 2500 per side; invalid journal is rejected. FR-COA-004. If not selected, document architecture decision and test allocations instead.'),
('AT-05 Product comparison','Surf Excel 1kg at 600 and Bonus 500g at 350, both Laundry Detergent; another item has unknown pack size.','Separate identities; 600/kg versus 700/kg. Unknown pack has no comparable-unit conclusion. FR-PRODUCT-001 to 003, FR-PRICE-001 to 002, FR-AI-006.'),
('AT-06 Period and savings','Dining 8400 this month versus 5900 last month; ask what changed and where savings are possible.','Increase 2500; hypothetical return to earlier level could reduce spending by 2500, with periods and assumptions. FR-AI-004, 007, 008, 009; NFR-DATA-004.'),
('AT-07 Maintenance','Change a saved expense date, amount and category; then delete it and repeat all relevant queries.','One coherent revision, then no active contribution to summaries or prices; retention follows policy. FR-LEDGER-005 to 006, NFR-DATA-002, NFR-PRIV-003.'),
('AT-08 Authorisation','A requests B\'s transaction or asks the assistant to ignore ownership using text embedded in a receipt.','No cross-account disclosure or write action. FR-AUTH-004, FR-AI-002 and 011, NFR-SEC-003.'),
('AT-09 Recovery','Interrupt save and retry the same request; separately time out OCR and AI.','One complete committed expense or none; clear processing and timeout state, manual recovery available. NFR-REL-001 to 002 and NFR-PERF-003.'),
('AT-10 Missing information','Ask a percentage change from zero, a price comparison without units and an answer from an empty ledger.','Undefined percentage, explicit comparison limitation and no-records explanation respectively. FR-PRICE-002, FR-AI-004, 006 and 010.'),
('AT-11 Optional release','For each selected optional feature, run its catalogue acceptance result plus relevant shared NFR checks.','Optional voice, labels, export, views, archive, localisation, categories, offline drafts and reminders have recorded pass/fail/deferred status. No deferred feature is described as implemented.')],[.65,2.4,2.97])
r.p('The identifiers in the scenario table are acceptance-scenario references, not additional formal requirements. Catalogue acceptance criteria remain authoritative for each FR and NFR. Record build, fixture, actor, steps, expected result, actual result, evidence and pass/fail status when tests run. Failures should link to a defect and the affected requirement ID. Source-reported interview statements are not test results.')
r.h('Remaining open issues and review actions',2)
tab('Open issues requiring human confirmation',['Issue','Required review','Effect on baseline'],[
('OI-01 Evidence provenance','Project team to locate interview dates, consent and source records; confirm actual Usman participant age.','Does not change the canonical persona age unless a controlled decision approves it.'),('OI-02 Academic review','Students verify the AI-assisted classification and supervisor reviews the proposed baseline. Confirm D3 submission date and the brief\'s conflicting 10-mark heading versus 20-mark total.','No supervisor endorsement or grading interpretation is claimed.'),('OI-03 Acceptance targets','Review proposed device, capacity, timing, extraction-fidelity, usability, credential and retention targets after a pilot.','Targets are explicit proposals; changes require logged rationale and affected IDs.'),('OI-04 Architecture and providers','Select delivery mode, database, OCR/model providers, budget and retention settings; decide whether double-entry journals are used.','Vendor-neutral contracts stay fixed. Balance is mandatory wherever journals are implemented.'),('OI-05 Optional release selection','Record which Should Have and Could Have features are included and obtain bilingual review if Urdu is selected.','No optional feature is guaranteed or silently upgraded.'),('OI-06 Evaluation resources','Acquire representative devices, annotated receipts and prospective trial participants.','No implementation, benchmark or real-user validation is claimed until evidence is collected.')],[.75,3.05,2.22])

r.h('Consolidated requirements catalogue')
r.p('This index is the canonical lookup for all 103 formal IDs. Detailed statements, acceptance criteria and sources are in their corresponding catalogues above. Counts exclude scope aliases and acceptance-scenario IDs. Priority letters below mean M: Must Have, S: Should Have, C: Could Have; they are abbreviations of the existing priority system, not a second classification.')
letter={'Must Have':'M','Should Have':'S','Could Have':'C'}
tab('Business requirement index',['ID','Title','Priority'],[(b[0],b[1],letter[b[6]]) for b in BR],[1.1,4.27,.65])
tab('Functional requirement index',['ID','Title','Priority'],[(f['id'],f['title'],letter[f['priority']]) for f in FR],[1.4,3.97,.65])
tab('Non functional requirement index',['ID','Title','Priority'],[(n['id'],n['title'],letter[n['priority']]) for n in NFR],[1.4,3.97,.65])
r.h('Conclusion')
r.p('DailyKhata now has a formal, traceable requirements specification for its approved personal and household expense-management scope. The internal audit finds complete capability coverage and continuity with governance, D1 v2.0 and D2 v2.0. The specification preserves the evidence limitations, optional priorities and current exclusions. Its next use is student and supervisor review followed by architecture and implementation work against the stated acceptance criteria. No software or stakeholder acceptance result is claimed by this document.')
r.h('References')
REFS=[
('[G1]','DailyKhata Project Scope. Version 2.0, 23 September 2026. 00_Project_Governance/DailyKhata_Project_Scope.docx. User-authorised baseline.'),
('[G2]','DailyKhata Documentation Standard. Version 2.0, 23 September 2026. 00_Project_Governance/DailyKhata_Documentation_Standard.docx.'),
('[G3]','DailyKhata Canonical Terminology. Version 2.0, 23 September 2026. 00_Project_Governance/DailyKhata_Canonical_Terminology.docx.'),
('[G4]','DailyKhata Decision Log. Version 2.0, 23 September 2026. 00_Project_Governance/DailyKhata_Decision_Log.docx. DEC-01 to DEC-20.'),
('[G5]','DailyKhata Consistency Audit. Version 2.0, 23 September 2026. 00_Project_Governance/DailyKhata_Consistency_Audit.docx.'),
('[D1]','DailyKhata Deliverable 1: Target Market & Audience Analysis. Version 2.0, 23 September 2026. 01_Deliverable_1/DailyKhata_Deliverable_1_v2.0.docx.'),
('[D2]','DailyKhata Deliverable 2: Problem Identification, Stakeholder Identification & Requirement Elicitation. Version 2.0, 23 September 2026. 02_Deliverable_2/DailyKhata_Deliverable_2_v2.0.docx. Evidence, candidate and stakeholder sections.'),
('[A3]','Beaconhouse National University. Deliverable 3: Requirements Specification. Five-page assignment brief, undated. 03_Deliverable_3/task/Deliverable 3.pdf. Rubric heading and total conflict; no mark interpretation is adopted.'),
('[H1]','DailyKhata. Original D1, dailykhata-d1.docx and six-page dailykhata-d1.pdf, 01_Deliverable_1. Historical source, undated.'),
('[H2]','DailyKhata. Original D2, dailykhata-d2.pdf, 02_Deliverable_2. Twelve pages, undated. Historical source-reported fieldwork, especially pp. 3 and 10-12.'),
('[M1]','Design Thinking.pdf. Six instructional slides, 02_Deliverable_2/task. Observation and interview methodology, not DailyKhata fieldwork.'),
('[M2]','Deliverable 1 and Deliverable 2 task.txt files in their respective task folders. Assignment context; D2 deadline does not establish a D3 submission date.'),
('[M3]','Important Links.txt, 02_Deliverable_2/task. Nineteen teaching-video links inventoried; video contents are not treated as project evidence.'),
('[U3]','Project owner instructions for DailyKhata Deliverable 3, supplied 23 September 2026. Scope continuity, formal identifiers, traceability, proposed targets and submission-document requirements.'),
('[X1]','OWASP Cheat Sheet Series. Password Storage Cheat Sheet. https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html. Accessed 23 September 2026. Supporting guidance for adaptive password hashing.'),
('[X2]','OWASP Cheat Sheet Series. Authorization Cheat Sheet. https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html. Accessed 23 September 2026. Supporting guidance for trusted-boundary authorisation checks.'),
('[X3]','OWASP Cheat Sheet Series. File Upload Cheat Sheet. https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html. Accessed 23 September 2026. Supporting guidance for validating uploaded content.')]
for key,text in REFS:r.p(key+' '+text)
r.h('Appendix glossary')
tab('Canonical terminology and abbreviations',['Term','Meaning in this specification'],[
('DailyKhata','The personal expense-management application defined by the approved scope.'),('OCR','Optical character recognition; proposes text from receipt images.'),('Receipt digitisation','Capture and transformation of a receipt into reviewable structured expense data.'),('Expense transaction','One confirmed expense with an owner, date, amount and categorised accounting allocations.'),('Line item','An individual purchase line within a receipt; distinct from the transaction total.'),('Automatic categorisation','A machine proposal for transaction or line-item category, subject to user confirmation or correction.'),('Expense category','User-understandable spending classification; its label is separate from its identity.'),('Chart of Accounts','Internal register of stable accounting accounts, types and references.'),('Semantic product classification','Mapping to canonical product types while preserving source text, brand and product identity.'),('Item-level price history','Historical recorded product prices with purchase context and comparable quantity where available.'),('AI Financial Assistant','Read-only conversational analysis of the current user\'s authorised DailyKhata records.'),('Localisation','Optional adaptation of interface language and presentation, including potential Urdu RTL support.'),('PKR and Rs.','Pakistani rupee; the baseline currency. Amounts use exact two-decimal representation.'),('RTL','Right-to-left text and interface presentation where required for Urdu.'),('FYP and SRS','Final Year Project and Software Requirements Specification.'),('Draft and commitment','An unconfirmed working record and the explicit transition to one saved expense. Drafts do not contribute to financial totals.')],[1.6,4.42])
r.d.core_properties.subject='DailyKhata authoritative requirements baseline'
# Check all authored text before serialisation.
alltext='\n'.join(p.text for p in r.d.paragraphs)+'\n'+'\n'.join(c.text for t in r.d.tables for row in t.rows for c in row.cells)
assert '\u2014' not in alltext
r.finish()
(WORK/'authored_text.txt').write_text(alltext,encoding='utf-8')
