from pathlib import Path
import sys,json,collections,hashlib
ROOT=Path('D:/BNU/SM7/FYP')
sys.path.insert(0,str(ROOT/'00_Project_Governance/reconstruction_work'))
from build import SCOPE,PERSONAS,DEFINITION,PROBLEM,EXCLUDED,FUTURE
WORK=ROOT/'03_Deliverable_3/requirements_work'
BR=[
('BR-001','Reduce recording effort','DailyKhata shall enable the primary user groups to maintain expense records without transcribing every available receipt field or requiring a receipt for a cash purchase.','Reduce repeated entry and omitted spending.','Ayesha and Hamza report capture friction; receipt and no-receipt paths address different purchases.','Primary account holders; secondary shopkeeper','Must Have','Representative users can save one corrected receipt and one no-receipt expense; compare observed task effort with their existing method without claiming an unmeasured improvement.'),
('BR-002','Maintain trustworthy expense records','DailyKhata shall preserve a coherent and correctable personal expense history suitable for structured long-term financial records.','Make recorded amounts and classifications dependable.','Incorrect categories and scattered records undermine later analysis; user correction and accounting mappings support continuity.','All account holders; project team','Must Have','Reviewed records can be retrieved, corrected and deleted without inconsistent category totals, product histories or accounting records.'),
('BR-003','Understand recorded spending','DailyKhata shall enable account holders to explain their recorded spending and identify possible savings using their own expense history.','Reduce the effort of assembling answers from separate records.','The approved assistant and summaries extend the original need for spending visibility; they are not evidence of financial outcomes.','Primary account holders; family beneficiaries','Must Have','A user obtains an accurate category total, period comparison and data-grounded suggestion from a controlled ledger fixture.'),
('BR-004','Support informed product comparison','DailyKhata shall enable account holders to compare historical purchase prices while retaining differences between products, brands and quantities.','Make recorded item prices useful for household decisions.','A product-type grouping supports related-product analysis but cannot establish that different brands or packs are identical.','Household budget managers; other account holders','Must Have','Detergent fixtures preserve separate identities, allow comparable-unit comparisons and explain missing-unit limitations.'),
('BR-005','Protect personal financial information','DailyKhata shall restrict access to personal expense information to its authorised account holder and the processing needed to deliver the requested service.','Support trust in storing sensitive expense records.','Privacy is an approved scope need; no new privacy interviews or certification claims are inferred.','All account holders; project team; service providers','Must Have','Cross-account access and assistant retrieval tests disclose no other account data; credential and storage controls pass inspection.'),
('BR-006','Support ordinary smartphone use','DailyKhata shall make the core expense workflows usable on an ordinary Android-class device, including understandable recovery from unavailable services.','Avoid dependence on high-end devices or uninterrupted cloud processing.','Low-effort recording requires readable review and visible failures; full offline operation is not core.','Primary account holders; secondary shopkeeper','Must Have','Core task and recovery scenarios pass the defined device and usability acceptance protocol.'),
('BR-007','Adapt presentation and sharing','DailyKhata shall support optional ways for account holders to understand and share their expense records in their preferred presentation.','Improve fit through optional language, labels, views and export.','D2 candidates and approved scope identify these as desirable extensions rather than minimum delivery conditions.','Account holders; family beneficiaries','Should Have','Implemented optional features preserve the same figures and classifications as the core ledger and pass their feature-specific checks.'),
('BR-008','Support flexible recording habits','DailyKhata shall provide optional support for expense-recording habits that need personal categories, temporary offline capture, reminders or household summaries.','Allow limited personal adaptation after the core workflow is complete.','These enhancements are scope-authorised Could Have features, not research-established commitments.','Account holders; family beneficiaries','Could Have','Each selected enhancement passes its acceptance scenario without requiring shared accounts or altering the baseline priorities.')]
EV={
'EV-01':('Reported Ayesha interview: repeated typing discourages receipt recording.','Original D2 p. 3; D2 v2.0 evidence register. No transcript.'),
'EV-02':('Reported Hamza interview: long forms create friction for small cash expenses.','Original D2 p. 3; D2 v2.0 evidence register. No transcript.'),
'EV-03':('Reported Usman interview: interest in spoken cash capture; example refers to customer payment.','Original D2 p. 3. Age 46 conflicts with design age 41; income context does not authorise sales functionality.'),
'EV-04':('Reported informal observations: entry is delayed or omitted and totals are reconstructed later.','Original D2 pp. 3 and 11; no observation counts or logs.'),
'EV-05':('Reported follow-up interviews: photograph or speech input and confirmation of proposed categories.','Original D2 pp. 10-11; no raw follow-up records or established visit date.'),
'EV-06':('Historical team-reported examination of Cashew, Wallet and an unnamed bank application.','Original D2 pp. 10-12; reportedly 30-45 minutes per member on Android. Versions, dates and screenshots absent; not current competitor research.'),
'EV-07':('Documentary authority: approved scope and project decisions supply required capabilities and priorities.','D2 v2.0 evidence register; current governance and owner instructions. This is not fieldwork.')}
DR={
'DR-01':('Receipt capture and review',['EV-01','EV-05','EV-07']),
'DR-02':('Manual and text capture',['EV-02','EV-03','EV-04','EV-05']),
'DR-03':('Optional voice capture',['EV-03','EV-05']),
'DR-04':('Categorisation with confirmation',['EV-05','EV-06']),
'DR-05':('Structured accounting records',['EV-07']),
'DR-06':('Ledger visibility and summaries',['EV-04','EV-07']),
'DR-07':('Product semantics and price history',['EV-06','EV-07']),
'DR-08':('AI Financial Assistant',['EV-07']),
'DR-09':('Identity and record maintenance',['EV-07']),
'DR-10':('Optional localisation export and labels',['EV-06','EV-07']),
'DR-11':('Optional views and receipt archive',['EV-04','EV-07']),
'DR-12':('Optional personal enhancements',['EV-07'])}
# Each functional record carries a behaviour, a specific oracle and a recovery outcome.
RAW='''AUTH|Account registration|SC-01|DR-09|BR-005|The system shall create a distinct user account from a valid, unused login identifier and accepted credentials.|Submitting an unused valid identifier creates one account; submitting the same identifier again creates none and returns a non-disclosing failure message.|Invalid or duplicate input leaves no partial account.
AUTH|Login|SC-01|DR-09|BR-005|The system shall establish an authenticated session only after successful credential verification.|Correct credentials open the account ledger; an incorrect password grants no session and does not disclose whether the account exists.|Rejected credentials retain the sign-in screen with a generic explanation.
AUTH|Logout|SC-01|DR-09|BR-005|The system shall terminate the current session when its user selects logout.|After logout, replaying the old session against the ledger and assistant is rejected and protected screens require login.|If the network is unavailable, local access ends immediately and the server session expires under the session policy.
AUTH|Authorised access boundary|SC-01,SC-27|DR-09|BR-005|The system shall authorise every protected operation against the current account identity.|Account A cannot read, change, delete, export or query an object belonging to B, including by modifying its identifier.|Unauthenticated or unauthorised requests return no protected payload.
PROFILE|Basic profile|SC-02|DR-09|BR-006|The system shall allow the account holder to view and update a display name without changing the stable account identity.|Change a display name, reopen the profile and verify the new name and unchanged ownership of earlier records.|An invalid or failed update preserves the previous value.
PROFILE|Basic settings|SC-02|DR-09|BR-006|The system shall persist the account holder's default summary month selection between authenticated sessions.|Select a supported month, sign out and back in, and verify that summaries use that month with its date range displayed.|An invalid month is rejected; a new account defaults to the current calendar month.
CAPTURE|Receipt photograph|SC-04|DR-01|BR-001|The system shall accept a camera photograph as input to a receipt draft.|Grant permission and take a photograph; its preview is associated with a new unsaved receipt draft.|Denied camera permission offers upload or manual entry without creating an expense.
CAPTURE|Receipt upload|SC-04|DR-01|BR-001|The system shall accept a supported image file selected by the user as input to a receipt draft.|A valid JPEG or PNG within the declared limit opens a draft preview; a renamed executable or oversized image is rejected.|Rejected files show the permitted formats and size, with a replacement or manual-entry path.
CAPTURE|Processing states and retry|SC-05|DR-01|BR-001,BR-006|The system shall show the current receipt-processing state and permit retry after a recoverable failure.|A controlled request passes through processing to review; a timeout shows failure and a retry creates no duplicate saved expense.|Retry remains user-triggered; a failed attempt retains the in-session draft while the session remains open.
CAPTURE|Receipt image archive|SS-06|DR-11|BR-007|The system shall retain a receipt image linked to its saved expense when the image archive feature is enabled.|Save an expense with its image and reopen it; only its account holder can view the corresponding image.|An unavailable archived image is identified separately from the valid structured expense; deletion follows the retention rule.
OCR|OCR text preservation|SC-05,SC-06|DR-01|BR-001|The system shall preserve the original OCR text separately from all user corrections and inferred values.|After processing a fixture and correcting an item name, the original extracted text remains retrievable in receipt review.|An unreadable image produces an explicit extraction failure, never invented source text.
OCR|Merchant extraction|SC-06|DR-01|BR-001|The system shall propose the merchant from receipt text when it can identify one.|A fixture with a recognisable merchant shows that value as proposed; a fixture without one shows an unknown merchant.|An uncertain merchant remains editable and is not required for manual fallback.
OCR|Date extraction|SC-06|DR-01|BR-001|The system shall propose a receipt date when available and flag ambiguous or missing dates for confirmation.|An unambiguous printed date is proposed; ambiguous numeric dates and absent dates require explicit user selection or confirmation.|The system does not silently replace an ambiguous receipt date with today's date.
OCR|Line item extraction|SC-06|DR-01|BR-001|The system shall construct reviewable line-item candidates from recognised purchase lines.|A controlled three-item extraction result displays three separately editable candidates and their corresponding source text.|Unrecognised lines remain visible in original text for user correction; headers are not silently accepted as products.
OCR|Quantity and unit extraction|SC-06|DR-01|BR-001,BR-004|The system shall associate recognised quantities and units with their line-item candidates without filling unknown values as inferred facts.|A two-pack fixture retains count two and its pack size separately; a missing quantity remains unknown.|Ambiguous units are marked for review and excluded from unit-price comparison until resolved.
OCR|Price extraction|SC-06|DR-01|BR-001|The system shall distinguish recognised unit prices from line totals in the receipt draft.|A line with quantity two, unit price 300 and line total 600 shows these in separate fields.|Where price type is ambiguous, the draft requests correction rather than assigning the same value to both fields.
OCR|Receipt total extraction|SC-06|DR-01|BR-001|The system shall propose the payable receipt total from recognised receipt text.|A fixture containing subtotal, discount and payable total proposes the payable total; the raw source remains visible.|Missing or conflicting totals prevent confirmation until the user supplies a valid total.
REVIEW|Draft review|SC-07|DR-01|BR-001,BR-002|The system shall present extracted values and uncertainty indicators for review before an expense can be committed.|A processed receipt opens review with merchant, date, items, quantities, prices, total and categories; no ledger row exists yet.|Unavailable fields remain visibly unknown and required corrections are identified.
REVIEW|Correction of extracted values|SC-07|DR-01|BR-002|The system shall allow the user to correct all extracted expense fields in the receipt draft.|Correct a merchant, date, quantity, price and total, add a missing item and remove a false item; review reflects every change while preserving source text.|Invalid numeric or date values show field-specific errors and do not overwrite valid draft values.
REVIEW|Discard and manual fallback|SC-07,SC-08|DR-01,DR-02|BR-001|The system shall allow the user to discard an unsaved receipt draft or continue it through manual entry.|Cancel a draft and verify no expense exists; in a separate failed extraction choose manual entry and supply the missing fields.|Leaving with unsaved changes requests confirmation before discarding them.
TXN|Manual quick expense entry|SC-08|DR-02|BR-001|The system shall create a reviewable expense draft from an amount, expense date and short description without requiring a receipt.|Enter Rs. 120, a valid date and rickshaw fare; review opens without a mandatory merchant, line-item list or image.|Missing amount or description leaves the draft unsaved and identifies the needed field.
TXN|Text based cash expense entry|SC-09|DR-02|BR-001|The system shall interpret a short cash-expense description into proposed fields for user review.|The input paid 120 for rickshaw yesterday proposes amount 120, the previous local date and transport context before confirmation.|An absent or ambiguous amount prompts clarification or manual completion instead of saving a guessed value.
TXN|Retrospective expense date|SC-03,SC-08,SC-09|DR-02,DR-06|BR-002|The system shall allow a past expense date independently of the record's creation timestamp.|Enter an expense today dated last month; last month's totals include it and the creation timestamp remains today.|Invalid dates are rejected; future-dated actual expenses are not committed in the baseline.
VOICE|Voice transcription|SC-10|DR-03|BR-001|The system shall produce an editable transcript from a user-initiated voice capture when voice entry is implemented.|With microphone permission, speak a cash expense and verify an editable transcript is displayed before interpretation.|Denied permission or failed recognition offers text entry; no expense is automatically saved.
VOICE|Voice expense draft|SC-10|DR-03|BR-001|The system shall convert a user-reviewed voice transcript into the same reviewable draft used for text-based cash expense entry.|Correct the recognised amount in a transcript and continue; the draft uses the corrected amount and awaits final confirmation.|Incomplete transcripts use the text-entry clarification path.
CAT|Transaction category proposal|SC-11|DR-04|BR-002|The system shall propose an expense category for each new transaction using its available description or receipt information.|A transport fixture receives a proposed transaction category; ambiguous input is marked uncertain and remains reviewable.|If classification is unavailable, the user selects a category from the local list before saving.
CAT|Line item category proposal|SC-11|DR-04|BR-002|The system shall propose an expense category independently for each receipt line item.|A mixed receipt proposes different categories for rice and detergent without forcing all items into the receipt's primary category.|Unclassified items remain flagged until the user selects their categories.
CAT|Category confirmation and correction|SC-12|DR-04|BR-002|The system shall require user confirmation of proposed categories and persist any user corrections with the expense.|Change detergent from Ration to Household Supplies and confirm; reopening preserves the correction and totals use Household Supplies.|A later model response cannot silently replace a confirmed user category.
CAT|Local category labels|SC-13|DR-04|BR-002,BR-006|The system shall present the canonical local category labels to users independently of internal account identifiers.|Category selection includes Ration, Transport, Dining, Utilities, Healthcare, Education, Entertainment and Household Supplies without requiring account codes.|An unknown machine label is not displayed as a substitute for a valid user-facing category.
CAT|Custom category labels|SS-03|DR-10|BR-007|The system shall let an account holder customise a category's displayed label without changing its category identity or accounting mapping.|Rename Ration to Groceries; historical totals and the Groceries Expense mapping are unchanged.|An empty or conflicting label is rejected with a correction prompt.
CAT|User created categories|SS-08|DR-12|BR-008|The system shall allow an account holder to create a personal expense category mapped to an existing appropriate expense account.|Create a valid category, select its supported account mapping through familiar category choices and use it on an expense.|No category can be saved without a valid mapping; this feature does not create arbitrary account classes.
COA|Internal account framework|SC-14|DR-05|BR-002|The system shall maintain stable account identifiers, names, account types and active status in an internal Chart of Accounts.|Inspect the account register: identifiers are unique and stable, each account has a recognised type, and the required expense and cash accounts exist.|Retiring an account cannot orphan historical expense records; account administration is not a user bookkeeping workflow.
COA|Category account mapping|SC-15|DR-05|BR-002|The system shall resolve every saved expense allocation to a valid accounting account through its category mapping.|Ration resolves to Groceries Expense and Household Supplies resolves to Household Supplies Expense for both new and historical allocations.|Missing or invalid mappings block commitment with a recoverable explanation.
COA|Accounting compatible storage|SC-16|DR-05|BR-002|The system shall store each committed expense with stable identifiers and accounting allocations that reconcile to its payable total.|Inspect a saved record: owner, expense date, creation time, PKR total, category allocations and account references are retrievable and allocations sum to the total.|A reconciliation failure leaves no partially committed expense or allocation.
COA|Balanced journals where used|SC-16|DR-05|BR-002|The system shall enforce equal total debits and credits for every committed journal wherever double-entry recording is implemented.|For cash groceries of Rs. 2500, the journal debits Groceries Expense 2500 and credits Cash 2500; an unbalanced journal is rejected.|If double-entry is not selected, document that architectural decision and still pass allocation-reconciliation checks; do not label allocations as balanced journals.
PRODUCT|Separate product identity fields|SC-22|DR-07|BR-004|The system shall preserve original text, corrected item name, product identity, brand, canonical product type, expense category and accounting classification as distinct attributes.|Surf Excel 1kg and Bonus 1kg remain separate products and brands after both are classified as Laundry Detergent.|An unknown brand or product identity remains unknown rather than inheriting another product's identity.
PRODUCT|Semantic product classification|SC-22|DR-07|BR-004|The system shall propose a canonical product type for a line item without merging distinct product identities.|Both detergent examples are grouped under Laundry Detergent for analysis while their separate histories remain available.|Uncertain classifications are marked provisional and are not treated as confirmed exact matches.
PRODUCT|Semantic correction|SC-22|DR-07|BR-004|The system shall allow the account holder to correct a product's inferred attributes and classification for the recorded line item.|Correct a wrong brand or type and reopen the line; subsequent analysis uses the corrected values and unchanged original text.|A correction cannot modify another account's products or silently rewrite unrelated historical purchases.
PRICE|Item level price history|SC-21|DR-07|BR-004|The system shall display a product's historical recorded prices with expense dates, quantities and source transactions.|Save the same confirmed product on two dates at different prices; history shows both records linked to their transactions.|Unknown product matches are identified as unresolved and are not silently merged into an exact-product history.
PRICE|Comparable product prices|SC-21,SC-22|DR-07|BR-004|The system shall compare prices of related products using equivalent quantities and compatible units where these are known.|A 1kg pack at Rs. 600 and 500g pack at Rs. 350 display Rs. 600/kg and Rs. 700/kg, retaining each brand and purchase date.|Without compatible units, display recorded prices and a comparison limitation, with no cheapest-per-unit conclusion.
LEDGER|Confirmed transaction commitment|SC-03,SC-12|DR-06,DR-04|BR-002|The system shall commit one expense transaction only after its valid draft and categories are explicitly confirmed by the user.|Confirm a reviewed draft once; one stable transaction ID is returned and its allocations reconcile to the expense total.|Validation failure or an interrupted save cannot create a partially saved ledger record.
LEDGER|Transaction detail|SC-17|DR-06|BR-002|The system shall display a saved expense transaction and its recorded line items, classifications and source information to its owner.|Open a mixed receipt from history and verify its date, merchant, total, items, corrected categories and original text where available.|A missing or inaccessible record shows an unavailable result without leaking other users' data.
LEDGER|Transaction history|SC-17|DR-06|BR-002|The system shall list the current account's saved expenses in descending expense-date order with a stable tie-break order.|Save expenses on two dates and several on the same date; repeated listing and pagination return each active transaction once.|An empty ledger displays an explicit empty state and an entry action.
LEDGER|Search and filtering|SC-18|DR-06|BR-002|The system shall return the account holder's expenses matching combined date-range, category and text criteria.|Filter a fixture by month and category and search merchant or item text; results include only matching owned expenses and clearing filters restores history.|Invalid date ranges request correction; no matches is distinguished from loading failure.
LEDGER|Edit saved transaction|SC-26|DR-09|BR-002|The system shall replace a saved expense's editable values through a validated user-confirmed revision that updates its dependent records.|Change a price, date and category; ledger detail, monthly totals, price history and accounting allocations all reflect the same revision.|A stale simultaneous edit requests reload or reconciliation instead of silently overwriting a later revision.
LEDGER|Delete saved transaction|SC-26|DR-09|BR-002|The system shall remove a user-confirmed deleted expense from active records and all derived spending and price results.|Delete a selected expense, refresh dashboard, history, price comparison and assistant query; none counts the deleted expense.|Cancellation changes nothing; failure identifies that deletion did not complete and does not claim success.
DASH|Category spending totals|SC-19|DR-06|BR-003|The system shall calculate category spending from active expense allocations for a selected date range without double counting receipt totals.|A receipt with Ration 100 and Household Supplies 50 contributes 100 and 50 respectively, with combined spending 150 rather than 300.|Unreconciled drafts do not contribute to category totals.
DASH|Monthly spending summary|SC-20|DR-06|BR-003|The system shall summarise active expenses within the selected calendar month using expense dates.|A month with expenses of 100, 250 and 150 shows total 500 and transaction count three, excluding adjacent dates and deleted records.|An empty month shows zero recorded spending and states that no expenses are recorded.
DASH|Dashboard overview|SC-25|DR-06|BR-003|The system shall display the selected month's total, category summary and recent expense transactions in a dashboard.|Load a fixture and verify displayed values match the monthly summary, category totals and newest transaction records.|If data cannot load, the dashboard shows an error or a labelled older snapshot, never an unexplained zero.
DASH|Spending visualisations|SS-04|DR-11|BR-007|The system shall present a simple labelled category-spending visualisation for the selected period when this optional view is implemented.|Each plotted category value matches the category-total fixture, and an equivalent text value is available.|An empty period shows an empty state rather than a misleading full chart.
DASH|Month comparison view|SS-05|DR-11|BR-007|The system shall display a dedicated comparison of two selected calendar months when this optional view is implemented.|Totals of 8400 and 5900 show an absolute difference of 2500 with both month labels.|When the earlier total is zero, percentage change is marked undefined instead of dividing by zero.
AI|Conversational financial query|SC-23,SC-24|DR-08|BR-003|The system shall accept natural-language financial questions and maintain the current conversation context for follow-up questions.|Ask for this month's Dining total and then compare it with last month; the second question retains the Dining context and states the resolved periods.|Ambiguous category or period references prompt clarification rather than a silent assumption presented as fact.
AI|Authorised transaction lookup|SC-23,SC-24|DR-08|BR-003,BR-005|The AI Financial Assistant shall answer transaction lookup questions using only the current account's authorised active records.|Ask for a merchant purchase in a date range; the answer identifies the matching records and ignores an identical record owned by another user.|No match is stated as no recorded match, not proof that the purchase did not occur.
AI|Spending and category summaries|SC-24|DR-08|BR-003|The AI Financial Assistant shall answer summary and category-analysis questions with totals computed from the applicable expense records.|For the Rs. 500 monthly fixture, the answer reports 500, the selected period and the contributing categories consistently with the dashboard.|Missing records or unavailable retrieval are disclosed; the assistant does not invent a total.
AI|Period comparison and explanation|SC-24|DR-08|BR-003|The AI Financial Assistant shall explain changes between requested periods using their recorded totals and category contributions.|Dining totals of 8400 and 5900 yield a 2500 increase; the answer names both periods and relates the change to recorded category amounts.|Unequal or incomplete periods are disclosed; zero baselines do not produce a defined percentage increase.
AI|Recurring spending and patterns|SC-24|DR-08|BR-003|The AI Financial Assistant shall identify repeated recorded expenses and describe their observed pattern with supporting dates and amounts.|A fixture with three monthly payments to one merchant yields a repeated-payment observation citing those entries.|The answer labels the observation as historical, does not promise future recurrence and creates no scheduled transaction.
AI|Semantic product price answers|SC-22,SC-24|DR-08,DR-07|BR-003,BR-004|The AI Financial Assistant shall answer product-price questions using separate product identities, semantic types and comparable historical quantities.|Ask which detergent was cheaper for me using the Rs. 600/kg and Rs. 700/kg fixture; the answer names the brands, dates, units and supported comparison.|Unknown quantities or identities produce a limitation rather than an unsupported cheapest-product claim.
AI|Unusually high recorded spending|SC-24|DR-08|BR-003|The AI Financial Assistant shall explain comparatively high recorded spending using an explicit comparison period or category basis.|Ask where spending was high; the answer identifies the chosen baseline, shows the relevant totals and describes the difference.|Without a suitable baseline the assistant requests one or says the available records do not support the comparison.
AI|Personalised saving suggestions|SC-24|DR-08|BR-003|The AI Financial Assistant shall provide optional general saving suggestions linked to the user's recorded spending and stated assumptions.|For Dining 8400 versus 5900, the answer may suggest returning to the earlier level and calculates potential reduction 2500, explicitly as a suggestion.|The assistant does not guarantee savings, fabricate preferences or propose executing a payment or investment transaction.
AI|Grounded answer presentation|SC-24,SC-27|DR-08|BR-003,BR-005|The AI Financial Assistant shall distinguish recorded facts, derived calculations and suggestions and identify the data period or supporting records for financial claims.|A test answer separates the recorded totals, their arithmetic difference and a suggested action; each numeric claim is reproducible from authorised records.|If the service cannot substantiate a claim, it omits or qualifies that claim rather than presenting it as a fact.
AI|Missing data and service failure|SC-24|DR-08|BR-003,BR-006|The AI Financial Assistant shall state when incomplete data or an unavailable service prevents a supported answer.|An empty ledger returns an insufficient-records explanation; a provider timeout returns a retryable service error without a fabricated answer.|Previously saved expenses remain accessible through ordinary history and summaries.
AI|Read only assistant authority|SC-24,SC-27|DR-08|BR-005|The AI Financial Assistant shall remain read-only with respect to expense records, payment systems and external financial accounts.|Prompts to delete expenses, move money or access a bank account cause no state change and explain the unsupported action.|Instructions embedded in receipt text cannot expand the assistant's data access or action permissions.
REPORT|Expense export|SC-29|DR-10|BR-007|The system shall export the account holder's selected expense records in at least one of CSV or PDF when export is implemented.|Export a selected period; the file identifies the period and includes date, description, category and amount with totals matching the same ledger selection.|A failed export shows failure and provides no misleading empty success file; both formats are not required.
REPORT|Household summary export|SS-11|DR-12|BR-008|The system shall export an account-holder-selected household expense summary when this optional feature is implemented.|Select household expenses or a household-labelled period and export category totals; the summary identifies the selection and matches those records.|Sharing remains an explicit action by the account holder; no invitation, recipient account or permission system is created.
LOC|Language selection|SC-28|DR-10|BR-007|The system shall allow selection of English or Urdu interface text when bilingual localisation is implemented.|Switch language and reopen the application; the chosen language is retained across the supported core screens without altering amounts or category identities.|Missing translations use an explicit English fallback and are recorded as localisation defects for acceptance review.
LOC|Urdu presentation|SC-28|DR-10|BR-007|The system shall render Urdu interface content with appropriate right-to-left layout while preserving readable numbers and product names when Urdu is implemented.|Inspect receipt review, history and assistant screens with mixed Urdu, Latin product names and PKR amounts; text remains legible and field associations are correct.|Unsupported rendering is identified as an unpassed optional feature, not described as validated Urdu support.
LOC|Urdu assistant interaction|SC-28|DR-10|BR-007|The AI Financial Assistant shall support Urdu questions and understandable Urdu answers for its core query types when Urdu interaction is implemented.|A bilingual reviewer checks equivalent English and Urdu questions against the same ledger fixture; amounts, periods and category meanings agree.|An unsupported question or translation failure uses a clear fallback and does not change the underlying financial result.
OFFLINE|Offline expense drafts|SS-09|DR-12|BR-008|The system shall retain manual or text expense drafts locally for later review and commitment when offline draft entry is implemented.|In flight mode create a draft, restart, reconnect and confirm it; exactly one owned expense is committed after review.|A queued draft is visibly unsaved and never contributes to spending totals before successful commitment.
REMIND|Expense reminder|SS-10|DR-12|BR-008|The system shall allow an account holder to enable or disable a local reminder to record expenses when reminders are implemented.|Enable a reminder for a test time and receive one notification; disable it and verify no later notification is scheduled.|Denied notification permission is explained; reminders create no expense transaction automatically.'''
FR=[]; seq=collections.Counter(); scope=dict((x[0],x[2]) for x in SCOPE)
for line in RAW.splitlines():
 g,title,sc,dr,br,statement,ac,failure=line.split('|');seq[g]+=1
 scopes=sc.split(','); priorities={scope[x] for x in scopes}; assert len(priorities)==1
 FR.append(dict(id=f'FR-{g}-{seq[g]:03}',group=g,title=title,scope=scopes,dr=dr.split(','),br=br.split(','),statement=statement,acceptance=ac,failure=failure,priority=priorities.pop()))
NRAW='''PERF|Ordinary interaction response|SC-30|Must Have|The application shall acknowledge a tap, navigation request or save action within one second in at least 19 of 20 trials on environment T1, excluding completion of external processing.|Instrument input and visible feedback timestamps across entry, review and history; acknowledgement can be a loading state and must not falsely indicate completion.
PERF|Ledger query response|SC-18,SC-20,SC-25,SC-30|Must Have|The system shall display search results and dashboard summaries within three seconds in at least 19 of 20 requests under T1 with the capacity fixture T2.|Measure from request initiation to complete visible result, including the test network; report cold and warm requests separately and all failures.
PERF|Bounded cloud waiting|SC-05,SC-24|Must Have|The system shall display processing feedback within one second and a retryable timeout state by 60 seconds for an OCR or assistant request that has not completed.|Use a delayed provider stub and verify feedback and timeout deadlines; record application, provider and end-to-end times separately during live trials. No universal successful cloud-response duration is promised.
SEC|Password protection|SC-01,SC-27|Must Have|The system shall store no plaintext or reversibly encrypted passwords and shall use salted adaptive password hashing where it manages passwords itself.|Inspect database and authentication configuration against documented current password-storage guidance [X1]; equivalent managed authentication must document its credential boundary.
SEC|Transport and secrets|SC-27|Must Have|The system shall protect remote financial-data communication with certificate-validated TLS and keep service secrets outside distributed clients and source control.|Inspect remote endpoints and deployment configuration; attempt invalid-certificate communication and scan the deliverable repository and client package for configured service secrets.
SEC|Object authorisation|SC-27|Must Have|The system shall reject every cross-account access attempt in the T3 authorisation matrix at the server or equivalent trusted data boundary.|Test direct identifiers, lists, uploads, exports, product history and assistant retrieval for two accounts; every unauthorised request returns no protected data. Client-only filtering is insufficient [X2].
SEC|Upload controls|SC-04,SC-27|Must Have|The system shall accept only verified JPEG and PNG receipt images of at most 10 MiB and shall reject invalid content before OCR processing.|Test extension, detected content, corrupt images, double extensions and size limits; confirm protected storage names do not enable executable public retrieval [X3].
SEC|Session protection|SC-01,SC-27|Must Have|The system shall expire an inactive session after 30 minutes and an active session after 24 hours, and shall throttle repeated failed logins after five failures within 15 minutes per account or equivalent non-enumerating control.|Use controlled clocks and repeated failures; verify expiry, generic errors and logout revocation. The throttle must not reveal account existence; its recovery interval is documented as 15 minutes.
PRIV|Service data minimisation|SC-27|Must Have|The system shall transmit to each external processor only the receipt content or authorised financial subset required for the requested operation and shall explain that processing before first use.|Inspect OCR and assistant payloads on T3 fixtures; no passwords, other-user data or unrelated receipt archive is sent. Record selected provider retention and training settings before deployment.
PRIV|Protected storage and logs|SC-27|Must Have|The system shall restrict stored expenses, images, local credentials and diagnostic logs through authenticated storage controls and shall exclude raw financial content and tokens from routine logs.|Inspect storage permissions and device credential storage; trigger failures and verify logs contain status and opaque references rather than receipt text, prompts or credentials. Document encryption-at-rest configuration for server financial storage.
PRIV|Deletion retention boundary|SC-26,SC-27|Must Have|The system shall remove a confirmed deleted expense from active retrieval before reporting success and erase its live structured content and associated retained image within 24 hours.|Inspect active and live storage at deletion and after 24 hours; any protected backup containing the record expires within 30 days and cannot be queried by the assistant. Document and test the deletion queue with a controlled clock.
USE|Core task completion|SC-08,SC-07,SC-30|Must Have|The system shall allow at least four of five representative trial users to complete manual entry, receipt correction and transaction lookup without facilitator intervention after a brief introduction.|Recruit across the three primary groups, record task outcomes and assistance; use consented trial data. This is a proposed acceptance target, not completed testing or a population claim.
USE|Correction and error clarity|SC-07,SC-12,SC-30|Must Have|The system shall identify the affected field and a recovery action for every invalid-input and service-error case in the specified acceptance suite.|Inspect amount, date, category, extraction and network failures; drafts retain valid inputs and no error screen relies only on a code or colour.
USE|Mobile readability|SC-30|Must Have|The system shall present core entry, review, history and assistant controls without horizontal page scrolling at a 360 CSS-pixel-equivalent viewport and 150 percent text scaling.|Inspect T1 screenshots and interact with all controls; tables may use an explicit contained scroll region, but totals and confirmation controls remain reachable and labelled.
REL|Atomic save and retry|SC-03,SC-16|Must Have|The system shall leave either one complete committed expense or no committed expense after each save interruption, and repeated submission of the same save request shall create no duplicates.|Inject failure before, during and after commitment, then retry the same operation identifier; count expenses and allocations and verify response matches the committed outcome.
REL|Service failure recovery|SC-05,SC-24,SC-30|Must Have|The system shall preserve already committed expense access when OCR or assistant processing fails and shall expose a user-triggered retry or manual-entry recovery path.|Disable each external dependency separately; history and existing summaries still work when their own data service is available, and no fabricated result replaces the failed operation.
DATA|Money and allocation integrity|SC-16,SC-19|Must Have|The system shall represent PKR money exactly to two decimal places and reconcile category allocations to each expense total with zero difference after documented rounding.|Run mixed-item, discount and rounding fixtures; compare stored minor-unit or exact-decimal totals, category sums and displayed values. Binary floating-point approximations must not create monetary discrepancies.
DATA|Revision consistency|SC-21,SC-26|Must Have|The system shall make all active ledger, summary, price-history and assistant retrieval results reflect a confirmed revision or deletion before the next fresh query returns.|Edit and delete fixtures, then query each dependent view; invalidate stale caches or label an older snapshot explicitly. An answer completed from a prior revision must be marked stale and refreshed.
DATA|Classification and provenance integrity|SC-12,SC-14,SC-15,SC-22|Must Have|The system shall preserve valid stable references and source provenance across every category, account and product correction in the acceptance suite.|Rename labels and revise inferred attributes; confirmed category mappings and original text remain intact and no record has a dangling account, category or owner reference.
DATA|Grounded financial calculations|SC-24|Must Have|The AI Financial Assistant shall reproduce all expected numeric results in the controlled T4 query suite and shall abstain or qualify when its authorised records do not support the requested conclusion.|Compare summary, difference, unit-price and zero-baseline answers with deterministic expected results; repeat each query three times. This finite-suite criterion is not a claim of perfect accuracy on arbitrary questions.
COMP|Android compatibility|SC-30|Must Have|The system shall complete the core acceptance workflows on an Android 11-class device with 4 GB RAM and on one newer Android version using the selected supported deployment mode.|Record actual device, OS, viewport and browser or application build; use a physical baseline device where available and disclose emulator-only evidence until physical validation is completed.
COMP|Localisation quality|SC-28|Should Have|The system shall pass bilingual review of all translated core-screen strings and mixed-direction layouts included in an implemented Urdu release.|Review English and Urdu for equivalent meaning, legible numbers and product names, RTL field associations and no untranslated required navigation labels; record reviewer and screenshots.
MAINT|Interface separation|SC-05,SC-24,SC-30|Must Have|The system shall document replaceable interfaces for OCR, assistant retrieval and persistent storage, with deterministic test substitutes for unavailable external services.|A team member runs receipt and assistant acceptance fixtures using substitute providers without changing ledger business rules; interface inputs, outputs and error states are documented.
MAINT|Requirements and regression records|SC-16,SC-26,SC-27|Must Have|The project shall retain an implementation and test reference for every delivered formal requirement ID and rerun affected integrity and authorisation checks after changes.|Inspect the delivery traceability register, versioned configuration and test results; deferred optional IDs have an explicit status and must not be silently deleted.
SCAL|Bounded academic capacity|SC-03,SC-30|Must Have|The system shall complete a 20-minute mixed read and write trial for 10 concurrent test accounts with 1000 expenses per account without lost or cross-account records.|Use T2 load with one request per account every five seconds, including 20 percent writes; reconcile all confirmed totals and report latency and resource use. This is a proposed academic capacity boundary, not a production-scale promise.'''
NFR=[]; ns=collections.Counter()
for line in NRAW.splitlines():
 g,title,sc,priority,statement,test=line.split('|');ns[g]+=1
 NFR.append(dict(id=f'NFR-{g}-{ns[g]:03}',group=g,title=title,scope=sc.split(','),priority=priority,statement=statement,test=test))
NM={n['id']:n for n in NFR}
NFR.append(dict(id='NFR-DATA-005',group='DATA',title='Receipt extraction fidelity',scope=['SC-05','SC-06'],priority='Must Have',statement='The system shall correctly propose at least 85 percent of legible payable totals and at least 70 percent of annotated purchase lines on the 20-receipt T5 fixture before user correction.',test='Compare output with independently checked manual annotations; a correct purchase line contains its readable item name and line total. Report merchant, date and quantity accuracy separately on fields actually present, all denominators, and unreadable-case failures. These are proposed pilot targets for the bounded printed-receipt set, not universal OCR guarantees.'))
NM={n['id']:n for n in NFR}
GROUPS={
'AUTH':('Authentication and access','Unauthenticated visitor for registration and login; account holder for logout.','Credentials are supplied through the application; protected data has an owner.','Register, sign in, sign out or request protected content.','Identity establishes the account boundary used by every later workflow.','NFR-SEC-001,NFR-SEC-002,NFR-SEC-003,NFR-SEC-005'),
'PROFILE':('Profile and settings','Authenticated account holder.','An account and session exist.','Open profile or settings and submit a change.','Small persistent preferences reduce repeated setup without creating household roles.','NFR-PERF-001,NFR-SEC-003'),
'CAPTURE':('Receipt capture','Authenticated account holder and camera or file picker.','A receipt image is available or can be photographed.','Select capture, upload, retry or an archived receipt.','Image acquisition supplies the same review workflow regardless of input path.','NFR-SEC-004,NFR-PRIV-002,NFR-PERF-003,NFR-REL-002'),
'OCR':('OCR and structured extraction','OCR component acting for the authenticated account holder.','A validated receipt image is attached to an in-session draft.','The user requests processing.','Extraction proposes data; it does not establish a confirmed financial record.','NFR-PERF-003,NFR-PRIV-001,NFR-DATA-003,NFR-REL-002'),
'REVIEW':('Receipt review and correction','Authenticated account holder.','A draft or failed extraction is available.','Review, change or discard proposed values.','The review boundary prevents uncertain machine output becoming an accepted expense.','NFR-USE-002,NFR-DATA-003,NFR-USE-001'),
'TXN':('Manual and text expense entry','Authenticated account holder.','The user knows the expense amount or can complete it manually.','Start manual entry, submit text or choose a past expense date.','No-receipt entry is core and cannot depend on optional speech or offline processing.','NFR-PERF-001,NFR-USE-001,NFR-USE-002,NFR-DATA-001'),
'VOICE':('Optional voice expense entry','Authenticated account holder and speech-recognition component.','Voice functionality is selected for implementation; microphone permission is available.','Start and stop voice capture, then accept or edit its transcript.','Voice supplies editable text and reuses the core confirmation path.','NFR-PRIV-001,NFR-USE-002,NFR-REL-002'),
'CAT':('Automatic categorisation','Authenticated account holder and category component.','A draft description or line item is present.','Create or correct an expense classification, or select an optional label action.','Category identity, local label and accounting account serve different purposes.','NFR-DATA-003,NFR-USE-002,NFR-SEC-003'),
'COA':('Chart of Accounts and accounting records','Internal accounting component acting for the account holder.','A reviewed expense is ready for commitment with valid category allocations.','Validate or persist accounting references for a save, revision or deletion.','Stable accounts support structured expense storage without an accounting interface.','NFR-DATA-001,NFR-DATA-002,NFR-DATA-003,NFR-REL-001'),
'PRODUCT':('Semantic product classification','Authenticated account holder and product-classification component.','A receipt line item and its available source attributes exist.','Classify or correct a recorded product.','Semantic grouping supports comparison while preserving brand and pack identity.','NFR-DATA-003,NFR-DATA-002,NFR-SEC-003'),
'PRICE':('Item level price history','Authenticated account holder.','Recorded items have dates and available product attributes.','Open a product history or request comparison.','Related-product comparison is useful only when quantities and provenance are visible.','NFR-DATA-001,NFR-DATA-002,NFR-DATA-003'),
'LEDGER':('Expense ledger and maintenance','Authenticated account holder.','For commitment, a valid reviewed draft exists; for maintenance, an owned saved expense exists.','Confirm, open, search, edit or delete an expense.','The ledger is the authoritative source for all current financial views.','NFR-REL-001,NFR-DATA-001,NFR-DATA-002,NFR-SEC-003,NFR-PERF-002'),
'DASH':('Dashboard and spending summaries','Authenticated account holder.','A period is selected; an empty ledger is also valid.','Open the dashboard or select a period or optional view.','All displays use one allocation rule so category and transaction totals reconcile.','NFR-PERF-002,NFR-DATA-001,NFR-DATA-002,NFR-USE-003'),
'AI':('AI Financial Assistant','Authenticated account holder, retrieval component and selected language model.','The session is authorised; records may be present, empty or incomplete.','Submit a financial question or follow-up.','Conversational interpretation relies on bounded retrieval and verified calculations.','NFR-DATA-004,NFR-SEC-003,NFR-PRIV-001,NFR-PERF-003,NFR-REL-002,NFR-DATA-002'),
'REPORT':('Optional export','Authenticated account holder.','The requested optional export capability is implemented and a selection is defined.','Request an export of owned records or household summary.','A user-controlled file provides sharing without shared household accounts.','NFR-SEC-003,NFR-DATA-001,NFR-DATA-002'),
'LOC':('Optional English and Urdu localisation','Authenticated account holder; bilingual reviewer during validation.','The relevant optional localisation features are implemented.','Select a language or ask a question in Urdu.','Translation changes presentation, never canonical category identity or financial arithmetic.','NFR-COMP-002,NFR-DATA-004,NFR-USE-003'),
'OFFLINE':('Optional offline drafts','Authenticated account holder with an established local session.','Offline draft support is implemented and local protected draft storage is available.','Create a draft without connectivity and later reconnect.','Only a reviewed committed expense enters financial summaries.','NFR-PRIV-002,NFR-REL-001,NFR-SEC-003'),
'REMIND':('Optional expense reminders','Account holder and device notification service.','Reminder support is implemented.','Enable, change or disable a reminder.','A recording prompt does not implement recurring expense generation.','NFR-USE-002,NFR-PRIV-002')}
deps={
'AUTH':[], 'PROFILE':['FR-AUTH-004'],'CAPTURE':['FR-AUTH-004'],
'OCR':['FR-CAPTURE-002'],'REVIEW':['FR-OCR-001'],'TXN':['FR-AUTH-004'],
'VOICE':['FR-TXN-002'],'CAT':['FR-AUTH-004'], 'COA':['FR-CAT-004'],
'PRODUCT':['FR-OCR-004'],'PRICE':['FR-PRODUCT-001','FR-LEDGER-001'],
'LEDGER':['FR-AUTH-004','FR-COA-003'],'DASH':['FR-LEDGER-001'],
'AI':['FR-AUTH-004','FR-LEDGER-001','FR-PRICE-002','FR-DASH-001'],
'REPORT':['FR-LEDGER-004'],'LOC':['FR-PROFILE-001','FR-AI-001'],
'OFFLINE':['FR-TXN-001','FR-LEDGER-001'],'REMIND':['FR-AUTH-004']}
for f in FR:
 f['evidence']=sorted({e for dr in f['dr'] for e in DR[dr][1]})
 f['nfr']=GROUPS[f['group']][5].split(',')
 f['dependencies']=deps[f['group']].copy()
# Dependencies denote an implemented service contract, not a forced execution order.
F={f['id']:f for f in FR}
F['FR-OCR-001']['dependencies']=['FR-CAPTURE-001','FR-CAPTURE-002']
F['FR-LEDGER-001']['dependencies']+=['FR-CAT-003']
F['FR-CAPTURE-004']['nfr']=['NFR-SEC-003','NFR-PRIV-002','NFR-PRIV-003']
F['FR-CAPTURE-001']['nfr']=['NFR-COMP-001','NFR-USE-002','NFR-SEC-004']
F['FR-VOICE-002']['dependencies']+=['FR-VOICE-001']
F['FR-REPORT-002']['dependencies']+=['FR-REPORT-001']
for f in FR:
 if f['group'] in ('AUTH','TXN','REVIEW','LEDGER','DASH'): f['nfr']+=['NFR-COMP-001']
 if f['group'] in ('OCR','AI'): f['nfr']+=['NFR-MAINT-001']
 if f['group']=='OCR': f['nfr']+=['NFR-DATA-005']
 if f['group'] in ('COA','LEDGER'): f['nfr']+=['NFR-MAINT-002','NFR-SCAL-001']
 f['nfr']=list(dict.fromkeys(f['nfr']))
F['FR-LEDGER-006']['nfr']+=['NFR-PRIV-003']

def validate():
 ids=[x['id'] for x in FR]+[x['id'] for x in NFR]+[x[0] for x in BR]
 assert len(ids)==len(set(ids)); assert len({f['statement'] for f in FR})==len(FR)
 bs={b[0] for b in BR}; nf=set(NM); errors=[]
 for f in FR:
  assert ' shall ' in f['statement'] and f['acceptance'] and f['failure']
  assert set(f['br'])<=bs and set(f['nfr'])<=nf and set(f['dependencies'])<=set(F)
  assert f['id'] not in f['dependencies']
  for d in f['dependencies']:
   rank={'Must Have':0,'Should Have':1,'Could Have':2}
   assert rank[F[d]['priority']]<=rank[f['priority']],(f['id'],d)
 covered={s for f in FR for s in f['scope']}|{s for n in NFR for s in n['scope']}
 assert covered==set(scope),(set(scope)-covered)
 assert {n['id'] for n in NFR}<={n for f in FR for n in f['nfr']}
 assert '\u2014' not in json.dumps([BR,FR,NFR,EV,DR,GROUPS],ensure_ascii=False)
 originals=json.loads((WORK/'source_manifest.json').read_text(encoding='utf-8-sig'))
 assert all(hashlib.sha256(Path(x['Path']).read_bytes()).hexdigest().upper()==x['SHA256'] for x in originals)
 result={'business':len(BR),'functional':len(FR),'nonfunctional':len(NFR),'functional_priorities':dict(collections.Counter(f['priority'] for f in FR)),'scope_capabilities':len(covered),'must_scope':sum(x[2]=='Must Have' for x in SCOPE),'duplicate_ids':0,'orphan_requirements':0,'priority_dependency_violations':0,'original_files_unchanged':len(originals),'em_dash_count':0,'status':'Internal model checks passed; implementation and stakeholder validation not performed'}
 (WORK/'requirements_model.json').write_text(json.dumps({'BR':BR,'FR':FR,'NFR':NFR,'EV':EV,'DR':DR},indent=2,ensure_ascii=False),encoding='utf-8')
 (WORK/'model_audit.json').write_text(json.dumps(result,indent=2),encoding='utf-8');print(json.dumps(result,indent=2))
if __name__=='__main__':validate()
